import { useState, useEffect, useRef } from 'react';
import { Link } from 'react-router-dom';
import Navbar from '@/components/layout/Navbar';
import Footer from '@/components/layout/Footer';
import { CodeBlock, Callout, OutputBlock, InlineCode } from '@/components/project/CodeBlock';
import { 
  ChevronRight, 
  Clock, 
  Users, 
  Star, 
  GitFork,
  ArrowLeft,
  Github,
  BookOpen,
  List,
  ExternalLink,
  CheckCircle2,
  Circle,
  Download,
  Loader2,
  Cloud
} from 'lucide-react';
import { Button } from '@/components/ui/button';

const sections = [
  { id: 'overview', title: 'Overview' },
  { id: 'prerequisites', title: 'Prerequisites' },
  { id: 'setup', title: 'AWS Setup' },
  { id: 'sagemaker', title: 'Amazon SageMaker' },
  { id: 'batch-transform', title: 'Batch Transform Jobs', parent: 'sagemaker' },
  { id: 'processing-jobs', title: 'Processing Jobs', parent: 'sagemaker' },
  { id: 's3-integration', title: 'S3 Integration' },
  { id: 'lambda-triggers', title: 'Lambda Triggers' },
  { id: 'scheduling', title: 'Scheduling with EventBridge' },
  { id: 'monitoring', title: 'Monitoring & Logging' },
  { id: 'cost-optimization', title: 'Cost Optimization' },
  { id: 'example', title: 'Complete Example' },
  { id: 'next-steps', title: 'Next Steps' },
];

const BatchDeploymentAWS = () => {
  const [activeSection, setActiveSection] = useState('overview');
  const [sidebarOpen, setSidebarOpen] = useState(false);
  const [progress, setProgress] = useState<string[]>([]);
  const [isDownloading, setIsDownloading] = useState(false);
  const contentRef = useRef<HTMLElement>(null);

  const handleDownloadPDF = async () => {
    setIsDownloading(true);
    
    const pdfContent = `
BATCH DEPLOYMENT ON AWS
============================

A Complete Guide to Deploying ML Models for Batch Inference on AWS

Difficulty: Intermediate
Estimated Time: 4 hours

TABLE OF CONTENTS
-----------------
1. Overview
2. Prerequisites
3. AWS Setup
4. Amazon SageMaker
   - Batch Transform Jobs
   - Processing Jobs
5. S3 Integration
6. Lambda Triggers
7. Scheduling with EventBridge
8. Monitoring & Logging
9. Cost Optimization
10. Complete Example
11. Next Steps

============================
OVERVIEW
============================

Learn how to deploy machine learning models for batch inference on Amazon Web Services.
This guide covers SageMaker Batch Transform, S3 integration, Lambda triggers, and 
cost optimization strategies.

---
Generated by MLCodex.dev
Batch Deployment on AWS
`;

    const blob = new Blob([pdfContent], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    
    const link = document.createElement('a');
    link.href = url;
    link.download = 'batch-deployment-aws.txt';
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
    
    setTimeout(() => {
      setIsDownloading(false);
    }, 1000);
  };

  useEffect(() => {
    const handleScroll = () => {
      const sectionElements = sections.map(s => ({
        id: s.id,
        element: document.getElementById(s.id)
      })).filter(s => s.element);

      for (const section of sectionElements.reverse()) {
        if (section.element) {
          const rect = section.element.getBoundingClientRect();
          if (rect.top <= 120) {
            setActiveSection(section.id);
            break;
          }
        }
      }
    };

    window.addEventListener('scroll', handleScroll);
    return () => window.removeEventListener('scroll', handleScroll);
  }, []);

  const scrollToSection = (id: string) => {
    const element = document.getElementById(id);
    if (element) {
      const offset = 100;
      const elementPosition = element.getBoundingClientRect().top + window.scrollY;
      window.scrollTo({ top: elementPosition - offset, behavior: 'smooth' });
    }
  };

  const toggleProgress = (sectionId: string) => {
    setProgress(prev => 
      prev.includes(sectionId) 
        ? prev.filter(id => id !== sectionId)
        : [...prev, sectionId]
    );
  };

  return (
    <div className="min-h-screen bg-background relative">
      <div className="noise-overlay" />
      <Navbar variant="simple" />
      
      <main className="pt-24 pb-20" ref={contentRef}>
        <div className="container mx-auto px-6">
          {/* Breadcrumb */}
          <div className="flex items-center gap-2 text-sm text-muted-foreground mb-8">
            <Link to="/docs" className="hover:text-foreground transition-colors">Docs</Link>
            <ChevronRight className="w-4 h-4" />
            <Link to="/docs/model-deployment" className="hover:text-foreground transition-colors">Model Deployment</Link>
            <ChevronRight className="w-4 h-4" />
            <span className="text-foreground">Batch Deployment - AWS</span>
          </div>

          <div className="flex gap-8 lg:gap-12">
            {/* Left Sidebar - Other Docs (Desktop) */}
            <aside className="hidden lg:block w-64 shrink-0">
              <div className="sticky top-28">
                <div className="flex items-center gap-2 mb-4">
                  <BookOpen className="w-4 h-4 text-muted-foreground" />
                  <span className="text-sm font-medium text-foreground">Related Docs</span>
                </div>
                <nav className="space-y-1">
                  {[
                    { slug: '/docs/batchdeployment/gcp', title: 'Batch Deploy on GCP' },
                    { slug: '/docs/onlinedeployment/aws', title: 'Online Deploy on AWS' },
                    { slug: '/docs/onlinedeployment/gcp', title: 'Online Deploy on GCP' },
                  ].map((doc) => (
                    <Link
                      key={doc.slug}
                      to={doc.slug}
                      className="block py-1.5 text-sm text-muted-foreground hover:text-foreground transition-colors"
                    >
                      {doc.title}
                    </Link>
                  ))}
                </nav>

                <Link 
                  to="/docs/model-deployment"
                  className="flex items-center gap-2 mt-4 text-sm text-muted-foreground hover:text-foreground transition-colors"
                >
                  View all deployment docs
                  <ChevronRight className="w-4 h-4" />
                </Link>

                {/* Progress Tracker */}
                <div className="mt-8 pt-6 border-t border-border">
                  <div className="text-sm font-medium text-foreground mb-3">Your Progress</div>
                  <div className="text-xs text-muted-foreground mb-2">
                    {progress.length} / {sections.filter(s => !s.parent).length} sections completed
                  </div>
                  <div className="w-full h-2 rounded-full bg-foreground/10">
                    <div 
                      className="h-full rounded-full bg-gradient-to-r from-teal-500 to-cyan-500 transition-all"
                      style={{ width: `${(progress.length / sections.filter(s => !s.parent).length) * 100}%` }}
                    />
                  </div>
                </div>

                {/* Quick Actions */}
                <div className="mt-6 pt-6 border-t border-border">
                  <div className="text-sm font-medium text-foreground mb-3">Quick Actions</div>
                  <div className="space-y-2">
                    <a 
                      href="https://github.com" 
                      target="_blank" 
                      rel="noopener noreferrer"
                      className="flex items-center gap-2 text-sm text-muted-foreground hover:text-foreground transition-colors py-1"
                    >
                      <Github className="w-4 h-4" />
                      View Source
                    </a>
                    <button 
                      onClick={handleDownloadPDF}
                      disabled={isDownloading}
                      className="flex items-center gap-2 text-sm text-muted-foreground hover:text-foreground transition-colors py-1 disabled:opacity-50"
                    >
                      {isDownloading ? (
                        <Loader2 className="w-4 h-4 animate-spin" />
                      ) : (
                        <Download className="w-4 h-4" />
                      )}
                      {isDownloading ? 'Downloading...' : 'Download PDF'}
                    </button>
                  </div>
                </div>
              </div>
            </aside>

            {/* Main Content */}
            <article className="flex-1 min-w-0 max-w-4xl">
              {/* Header */}
              <header className="mb-12">
                <div className="mb-6">
                  <div className="flex items-center gap-3 mb-4">
                    <div className="w-12 h-12 rounded-xl bg-orange-500/10 border border-orange-500/20 flex items-center justify-center">
                      <Cloud className="w-6 h-6 text-orange-400" />
                    </div>
                    <span className="text-[10px] px-2.5 py-1 rounded-full bg-orange-500/10 text-orange-400 border border-orange-500/20 font-medium uppercase tracking-wider">
                      AWS
                    </span>
                  </div>
                  <h1 className="text-4xl lg:text-5xl font-bold tracking-tight mb-4">
                    Batch Deployment on AWS
                  </h1>
                  <p className="text-lg text-muted-foreground leading-relaxed">
                    Deploy ML models for batch inference using Amazon SageMaker, S3, Lambda, and EventBridge. 
                    Learn to process large datasets efficiently with cost optimization strategies.
                  </p>
                </div>

                {/* Meta Info */}
                <div className="flex flex-wrap items-center gap-6 text-sm text-muted-foreground mb-6">
                  <div className="flex items-center gap-1.5">
                    <Clock className="w-4 h-4" />
                    <span>4 hours</span>
                  </div>
                  <div className="flex items-center gap-1.5">
                    <Star className="w-4 h-4" />
                    <span>1,523 stars</span>
                  </div>
                  <div className="flex items-center gap-1.5">
                    <GitFork className="w-4 h-4" />
                    <span>412 forks</span>
                  </div>
                  <div className="flex items-center gap-1.5">
                    <Users className="w-4 h-4" />
                    <span>89 contributors</span>
                  </div>
                  <span className="px-2.5 py-1 rounded-full bg-amber-400/10 text-amber-400 border border-amber-400/20 text-xs font-medium">
                    Intermediate
                  </span>
                </div>

                {/* Action Buttons */}
                <div className="flex flex-wrap gap-3">
                  <Button variant="hero" size="lg">
                    <Github className="w-4 h-4 mr-2" />
                    View on GitHub
                  </Button>
                  <Button 
                    variant="outline" 
                    size="lg" 
                    className="border-foreground/20 hover:bg-foreground/5"
                    onClick={handleDownloadPDF}
                    disabled={isDownloading}
                  >
                    {isDownloading ? (
                      <Loader2 className="w-4 h-4 mr-2 animate-spin" />
                    ) : (
                      <Download className="w-4 h-4 mr-2" />
                    )}
                    {isDownloading ? 'Downloading...' : 'Download PDF'}
                  </Button>
                </div>
              </header>

              {/* Overview Section */}
              <section id="overview" className="mb-16">
                <h2 className="text-2xl font-bold text-foreground mb-4 flex items-center gap-3">
                  <button 
                    onClick={() => toggleProgress('overview')}
                    className="text-muted-foreground hover:text-teal-500 transition-colors"
                  >
                    {progress.includes('overview') ? (
                      <CheckCircle2 className="w-6 h-6 text-teal-500" />
                    ) : (
                      <Circle className="w-6 h-6" />
                    )}
                  </button>
                  Overview
                </h2>
                <p className="text-muted-foreground leading-relaxed mb-4">
                  Batch deployment is ideal for processing large volumes of data where real-time predictions aren't required. 
                  AWS provides robust services for batch ML inference, including SageMaker Batch Transform, which can process 
                  terabytes of data efficiently.
                </p>
                <p className="text-muted-foreground leading-relaxed mb-4">
                  In this guide, you'll learn how to set up a complete batch inference pipeline on AWS, from storing your 
                  data in S3 to scheduling automated batch jobs with EventBridge.
                </p>

                <div className="grid grid-cols-1 md:grid-cols-3 gap-4 mt-8">
                  <div className="p-4 rounded-xl bg-card/50 border border-border">
                    <div className="text-2xl font-bold text-foreground mb-1">99.9%</div>
                    <div className="text-sm text-muted-foreground">SLA Availability</div>
                  </div>
                  <div className="p-4 rounded-xl bg-card/50 border border-border">
                    <div className="text-2xl font-bold text-foreground mb-1">TB+</div>
                    <div className="text-sm text-muted-foreground">Data Processing</div>
                  </div>
                  <div className="p-4 rounded-xl bg-card/50 border border-border">
                    <div className="text-2xl font-bold text-foreground mb-1">Auto</div>
                    <div className="text-sm text-muted-foreground">Scaling</div>
                  </div>
                </div>
              </section>

              {/* Prerequisites Section */}
              <section id="prerequisites" className="mb-16">
                <h2 className="text-2xl font-bold text-foreground mb-4 flex items-center gap-3">
                  <button 
                    onClick={() => toggleProgress('prerequisites')}
                    className="text-muted-foreground hover:text-teal-500 transition-colors"
                  >
                    {progress.includes('prerequisites') ? (
                      <CheckCircle2 className="w-6 h-6 text-teal-500" />
                    ) : (
                      <Circle className="w-6 h-6" />
                    )}
                  </button>
                  Prerequisites
                </h2>
                <p className="text-muted-foreground leading-relaxed mb-4">
                  Before starting this guide, make sure you have:
                </p>
                <ul className="space-y-3 text-muted-foreground">
                  <li className="flex items-start gap-3">
                    <ChevronRight className="w-5 h-5 text-teal-500 shrink-0 mt-0.5" />
                    <span><strong className="text-foreground">AWS Account</strong> — With appropriate IAM permissions for SageMaker, S3, Lambda, and EventBridge</span>
                  </li>
                  <li className="flex items-start gap-3">
                    <ChevronRight className="w-5 h-5 text-teal-500 shrink-0 mt-0.5" />
                    <span><strong className="text-foreground">AWS CLI</strong> — Installed and configured with your credentials</span>
                  </li>
                  <li className="flex items-start gap-3">
                    <ChevronRight className="w-5 h-5 text-teal-500 shrink-0 mt-0.5" />
                    <span><strong className="text-foreground">Python 3.8+</strong> — With boto3 and sagemaker SDK installed</span>
                  </li>
                  <li className="flex items-start gap-3">
                    <ChevronRight className="w-5 h-5 text-teal-500 shrink-0 mt-0.5" />
                    <span><strong className="text-foreground">Trained ML Model</strong> — A model ready for deployment (we'll use a sample model)</span>
                  </li>
                </ul>

                <Callout type="tip" title="Free Tier Available">
                  AWS offers a free tier for SageMaker that includes 250 hours of t2.medium notebook instance usage 
                  per month for the first two months. Perfect for learning!
                </Callout>
              </section>

              {/* Setup Section */}
              <section id="setup" className="mb-16">
                <h2 className="text-2xl font-bold text-foreground mb-4 flex items-center gap-3">
                  <button 
                    onClick={() => toggleProgress('setup')}
                    className="text-muted-foreground hover:text-teal-500 transition-colors"
                  >
                    {progress.includes('setup') ? (
                      <CheckCircle2 className="w-6 h-6 text-teal-500" />
                    ) : (
                      <Circle className="w-6 h-6" />
                    )}
                  </button>
                  AWS Setup
                </h2>
                <p className="text-muted-foreground leading-relaxed mb-4">
                  First, let's set up the required AWS resources and install the necessary Python packages.
                </p>

                <CodeBlock 
                  language="bash"
                  filename="terminal"
                  code={`# Install required packages
pip install boto3 sagemaker pandas

# Configure AWS CLI (if not already done)
aws configure`}
                  showLineNumbers={false}
                />

                <p className="text-muted-foreground leading-relaxed my-4">
                  Now let's set up our Python environment and initialize the SageMaker session:
                </p>

                <CodeBlock 
                  filename="setup.py"
                  code={`import boto3
import sagemaker
from sagemaker import get_execution_role

# Initialize SageMaker session
sagemaker_session = sagemaker.Session()

# Get the execution role (for notebook instances)
# Or specify your role ARN directly
try:
    role = get_execution_role()
except ValueError:
    role = 'arn:aws:iam::YOUR_ACCOUNT_ID:role/SageMakerRole'

# Define S3 bucket for data and models
bucket = sagemaker_session.default_bucket()
prefix = 'batch-deployment-demo'

print(f"SageMaker Role: {role}")
print(f"S3 Bucket: {bucket}")`}
                />

                <Callout type="info" title="IAM Role Permissions">
                  Your SageMaker execution role needs permissions for S3 access, SageMaker operations, 
                  and CloudWatch logging. Use the <InlineCode>AmazonSageMakerFullAccess</InlineCode> managed 
                  policy for development.
                </Callout>
              </section>

              {/* SageMaker Section */}
              <section id="sagemaker" className="mb-16">
                <h2 className="text-2xl font-bold text-foreground mb-4 flex items-center gap-3">
                  <button 
                    onClick={() => toggleProgress('sagemaker')}
                    className="text-muted-foreground hover:text-teal-500 transition-colors"
                  >
                    {progress.includes('sagemaker') ? (
                      <CheckCircle2 className="w-6 h-6 text-teal-500" />
                    ) : (
                      <Circle className="w-6 h-6" />
                    )}
                  </button>
                  Amazon SageMaker
                </h2>
                <p className="text-muted-foreground leading-relaxed mb-8">
                  Amazon SageMaker provides two main approaches for batch inference: Batch Transform Jobs 
                  and Processing Jobs. Let's explore both.
                </p>

                {/* Batch Transform Jobs */}
                <div id="batch-transform" className="mb-12">
                  <h3 className="text-xl font-semibold text-foreground mb-4">Batch Transform Jobs</h3>
                  <p className="text-muted-foreground leading-relaxed mb-4">
                    Batch Transform is optimized for getting inferences on large datasets. It automatically 
                    manages the compute resources and distributes the workload.
                  </p>

                  <CodeBlock 
                    filename="batch_transform.py"
                    code={`from sagemaker.transformer import Transformer

# Create a transformer from your trained model
transformer = Transformer(
    model_name='my-trained-model',
    instance_count=2,
    instance_type='ml.m5.xlarge',
    output_path=f's3://{bucket}/{prefix}/output',
    sagemaker_session=sagemaker_session,
    strategy='MultiRecord',  # Process multiple records per request
    max_payload=6,           # Max payload size in MB
    max_concurrent_transforms=4
)

# Start the batch transform job
transformer.transform(
    data=f's3://{bucket}/{prefix}/input',
    content_type='text/csv',
    split_type='Line',
    wait=True,
    logs=True
)

print(f"Output available at: {transformer.output_path}")`}
                  />

                  <div className="grid grid-cols-1 md:grid-cols-2 gap-4 mt-6">
                    <div className="p-4 rounded-xl bg-blue-500/10 border border-blue-500/20">
                      <div className="font-semibold text-blue-400 mb-1">MultiRecord Strategy</div>
                      <div className="text-sm text-muted-foreground">Batches multiple records per inference request for efficiency</div>
                    </div>
                    <div className="p-4 rounded-xl bg-purple-500/10 border border-purple-500/20">
                      <div className="font-semibold text-purple-400 mb-1">Auto Scaling</div>
                      <div className="text-sm text-muted-foreground">Distributes workload across multiple instances automatically</div>
                    </div>
                  </div>
                </div>

                {/* Processing Jobs */}
                <div id="processing-jobs" className="mb-12">
                  <h3 className="text-xl font-semibold text-foreground mb-4">Processing Jobs</h3>
                  <p className="text-muted-foreground leading-relaxed mb-4">
                    For more complex batch workflows that include data preprocessing and postprocessing, 
                    use SageMaker Processing Jobs:
                  </p>

                  <CodeBlock 
                    filename="processing_job.py"
                    code={`from sagemaker.processing import ScriptProcessor, ProcessingInput, ProcessingOutput

# Create a script processor
processor = ScriptProcessor(
    role=role,
    image_uri='YOUR_ECR_IMAGE_URI',  # Or use built-in containers
    command=['python3'],
    instance_count=2,
    instance_type='ml.m5.xlarge',
    volume_size_in_gb=50,
    sagemaker_session=sagemaker_session
)

# Run the processing job
processor.run(
    code='processing_script.py',
    inputs=[
        ProcessingInput(
            source=f's3://{bucket}/{prefix}/raw-data',
            destination='/opt/ml/processing/input'
        )
    ],
    outputs=[
        ProcessingOutput(
            source='/opt/ml/processing/output',
            destination=f's3://{bucket}/{prefix}/processed-data'
        )
    ],
    arguments=['--batch-size', '1000']
)`}
                  />
                </div>
              </section>

              {/* S3 Integration Section */}
              <section id="s3-integration" className="mb-16">
                <h2 className="text-2xl font-bold text-foreground mb-4 flex items-center gap-3">
                  <button 
                    onClick={() => toggleProgress('s3-integration')}
                    className="text-muted-foreground hover:text-teal-500 transition-colors"
                  >
                    {progress.includes('s3-integration') ? (
                      <CheckCircle2 className="w-6 h-6 text-teal-500" />
                    ) : (
                      <Circle className="w-6 h-6" />
                    )}
                  </button>
                  S3 Integration
                </h2>
                <p className="text-muted-foreground leading-relaxed mb-4">
                  Amazon S3 serves as the central data store for batch inference. Here's how to set up 
                  efficient data pipelines:
                </p>

                <CodeBlock 
                  filename="s3_utils.py"
                  code={`import boto3
import pandas as pd
from io import StringIO

s3_client = boto3.client('s3')

def upload_data_to_s3(df: pd.DataFrame, bucket: str, key: str):
    """Upload a DataFrame to S3 as CSV."""
    csv_buffer = StringIO()
    df.to_csv(csv_buffer, index=False)
    
    s3_client.put_object(
        Bucket=bucket,
        Key=key,
        Body=csv_buffer.getvalue()
    )
    print(f"Uploaded to s3://{bucket}/{key}")

def download_results_from_s3(bucket: str, prefix: str):
    """Download all results from an S3 prefix."""
    paginator = s3_client.get_paginator('list_objects_v2')
    
    results = []
    for page in paginator.paginate(Bucket=bucket, Prefix=prefix):
        for obj in page.get('Contents', []):
            response = s3_client.get_object(Bucket=bucket, Key=obj['Key'])
            content = response['Body'].read().decode('utf-8')
            results.append(pd.read_csv(StringIO(content)))
    
    return pd.concat(results, ignore_index=True)

# Example usage
input_df = pd.DataFrame({
    'feature1': [1, 2, 3, 4, 5],
    'feature2': [0.1, 0.2, 0.3, 0.4, 0.5]
})

upload_data_to_s3(input_df, bucket, f'{prefix}/input/data.csv')`}
                />
              </section>

              {/* Lambda Triggers Section */}
              <section id="lambda-triggers" className="mb-16">
                <h2 className="text-2xl font-bold text-foreground mb-4 flex items-center gap-3">
                  <button 
                    onClick={() => toggleProgress('lambda-triggers')}
                    className="text-muted-foreground hover:text-teal-500 transition-colors"
                  >
                    {progress.includes('lambda-triggers') ? (
                      <CheckCircle2 className="w-6 h-6 text-teal-500" />
                    ) : (
                      <Circle className="w-6 h-6" />
                    )}
                  </button>
                  Lambda Triggers
                </h2>
                <p className="text-muted-foreground leading-relaxed mb-4">
                  Use AWS Lambda to trigger batch jobs automatically when new data arrives in S3:
                </p>

                <CodeBlock 
                  filename="lambda_trigger.py"
                  code={`import json
import boto3

sagemaker_client = boto3.client('sagemaker')

def lambda_handler(event, context):
    """Trigger batch transform when new data arrives in S3."""
    
    # Get the S3 bucket and key from the event
    bucket = event['Records'][0]['s3']['bucket']['name']
    key = event['Records'][0]['s3']['object']['key']
    
    # Only process files in the input folder
    if not key.startswith('batch-deployment-demo/input/'):
        return {'statusCode': 200, 'body': 'Skipped'}
    
    # Start batch transform job
    job_name = f"batch-job-{context.aws_request_id[:8]}"
    
    response = sagemaker_client.create_transform_job(
        TransformJobName=job_name,
        ModelName='my-trained-model',
        TransformInput={
            'DataSource': {
                'S3DataSource': {
                    'S3DataType': 'S3Prefix',
                    'S3Uri': f's3://{bucket}/{key}'
                }
            },
            'ContentType': 'text/csv',
            'SplitType': 'Line'
        },
        TransformOutput={
            'S3OutputPath': f's3://{bucket}/batch-deployment-demo/output/'
        },
        TransformResources={
            'InstanceType': 'ml.m5.xlarge',
            'InstanceCount': 1
        }
    )
    
    return {
        'statusCode': 200,
        'body': json.dumps(f"Started job: {job_name}")
    }`}
                />

                <Callout type="warning" title="Lambda Timeout">
                  This Lambda function only starts the batch job—it doesn't wait for completion. 
                  Batch transform jobs can take hours for large datasets, well beyond Lambda's 15-minute limit.
                </Callout>
              </section>

              {/* Scheduling Section */}
              <section id="scheduling" className="mb-16">
                <h2 className="text-2xl font-bold text-foreground mb-4 flex items-center gap-3">
                  <button 
                    onClick={() => toggleProgress('scheduling')}
                    className="text-muted-foreground hover:text-teal-500 transition-colors"
                  >
                    {progress.includes('scheduling') ? (
                      <CheckCircle2 className="w-6 h-6 text-teal-500" />
                    ) : (
                      <Circle className="w-6 h-6" />
                    )}
                  </button>
                  Scheduling with EventBridge
                </h2>
                <p className="text-muted-foreground leading-relaxed mb-4">
                  Schedule batch jobs to run at specific times using Amazon EventBridge:
                </p>

                <CodeBlock 
                  filename="eventbridge_schedule.py"
                  code={`import boto3

events_client = boto3.client('events')
lambda_client = boto3.client('lambda')

# Create a rule that runs daily at midnight UTC
rule_response = events_client.put_rule(
    Name='DailyBatchInference',
    ScheduleExpression='cron(0 0 * * ? *)',  # Every day at midnight
    State='ENABLED',
    Description='Triggers daily batch inference job'
)

# Add Lambda as target
events_client.put_targets(
    Rule='DailyBatchInference',
    Targets=[
        {
            'Id': 'BatchInferenceTrigger',
            'Arn': 'arn:aws:lambda:REGION:ACCOUNT:function:batch-trigger',
            'Input': json.dumps({
                'source': 'scheduled',
                'input_path': f's3://{bucket}/{prefix}/daily-input/'
            })
        }
    ]
)

# Grant EventBridge permission to invoke Lambda
lambda_client.add_permission(
    FunctionName='batch-trigger',
    StatementId='EventBridgeInvoke',
    Action='lambda:InvokeFunction',
    Principal='events.amazonaws.com',
    SourceArn=rule_response['RuleArn']
)`}
                />
              </section>

              {/* Monitoring Section */}
              <section id="monitoring" className="mb-16">
                <h2 className="text-2xl font-bold text-foreground mb-4 flex items-center gap-3">
                  <button 
                    onClick={() => toggleProgress('monitoring')}
                    className="text-muted-foreground hover:text-teal-500 transition-colors"
                  >
                    {progress.includes('monitoring') ? (
                      <CheckCircle2 className="w-6 h-6 text-teal-500" />
                    ) : (
                      <Circle className="w-6 h-6" />
                    )}
                  </button>
                  Monitoring & Logging
                </h2>
                <p className="text-muted-foreground leading-relaxed mb-4">
                  Monitor your batch jobs using CloudWatch metrics and logs:
                </p>

                <CodeBlock 
                  filename="monitoring.py"
                  code={`import boto3
from datetime import datetime, timedelta

cloudwatch = boto3.client('cloudwatch')
logs_client = boto3.client('logs')

def get_job_metrics(job_name: str):
    """Get CloudWatch metrics for a batch transform job."""
    
    end_time = datetime.utcnow()
    start_time = end_time - timedelta(hours=24)
    
    response = cloudwatch.get_metric_statistics(
        Namespace='AWS/SageMaker',
        MetricName='Invocations',
        Dimensions=[
            {'Name': 'TransformJobName', 'Value': job_name}
        ],
        StartTime=start_time,
        EndTime=end_time,
        Period=300,  # 5 minutes
        Statistics=['Sum', 'Average']
    )
    
    return response['Datapoints']

def get_job_logs(job_name: str):
    """Retrieve logs for a batch transform job."""
    
    log_group = f'/aws/sagemaker/TransformJobs'
    log_stream = job_name
    
    response = logs_client.get_log_events(
        logGroupName=log_group,
        logStreamName=log_stream,
        limit=100
    )
    
    return [event['message'] for event in response['events']]

# Set up CloudWatch alarm for job failures
cloudwatch.put_metric_alarm(
    AlarmName='BatchJobFailures',
    MetricName='TransformJobsFailed',
    Namespace='AWS/SageMaker',
    Statistic='Sum',
    Period=300,
    EvaluationPeriods=1,
    Threshold=1,
    ComparisonOperator='GreaterThanOrEqualToThreshold',
    AlarmActions=['arn:aws:sns:REGION:ACCOUNT:alerts']
)`}
                />
              </section>

              {/* Cost Optimization Section */}
              <section id="cost-optimization" className="mb-16">
                <h2 className="text-2xl font-bold text-foreground mb-4 flex items-center gap-3">
                  <button 
                    onClick={() => toggleProgress('cost-optimization')}
                    className="text-muted-foreground hover:text-teal-500 transition-colors"
                  >
                    {progress.includes('cost-optimization') ? (
                      <CheckCircle2 className="w-6 h-6 text-teal-500" />
                    ) : (
                      <Circle className="w-6 h-6" />
                    )}
                  </button>
                  Cost Optimization
                </h2>
                <p className="text-muted-foreground leading-relaxed mb-4">
                  Reduce costs while maintaining performance with these strategies:
                </p>

                <div className="space-y-4 mb-6">
                  <div className="p-4 rounded-xl bg-card/50 border border-border">
                    <h4 className="font-semibold text-foreground mb-2">Use Spot Instances</h4>
                    <p className="text-sm text-muted-foreground mb-3">
                      Spot instances can reduce costs by up to 90% for batch workloads that can tolerate interruptions.
                    </p>
                    <CodeBlock 
                      filename="spot_instances.py"
                      code={`transformer = Transformer(
    model_name='my-model',
    instance_count=2,
    instance_type='ml.m5.xlarge',
    use_spot_instances=True,
    max_wait=3600,  # Max wait time in seconds
    output_path=f's3://{bucket}/{prefix}/output'
)`}
                    />
                  </div>

                  <div className="p-4 rounded-xl bg-card/50 border border-border">
                    <h4 className="font-semibold text-foreground mb-2">Right-size Instances</h4>
                    <p className="text-sm text-muted-foreground">
                      Start with smaller instances and scale up based on actual memory and CPU utilization. 
                      Use <InlineCode>ml.m5.large</InlineCode> for testing, then benchmark with larger instances.
                    </p>
                  </div>

                  <div className="p-4 rounded-xl bg-card/50 border border-border">
                    <h4 className="font-semibold text-foreground mb-2">Optimize Data Format</h4>
                    <p className="text-sm text-muted-foreground">
                      Use compressed formats like Parquet or Gzip CSV to reduce data transfer costs and 
                      improve processing speed.
                    </p>
                  </div>
                </div>
              </section>

              {/* Complete Example Section */}
              <section id="example" className="mb-16">
                <h2 className="text-2xl font-bold text-foreground mb-4 flex items-center gap-3">
                  <button 
                    onClick={() => toggleProgress('example')}
                    className="text-muted-foreground hover:text-teal-500 transition-colors"
                  >
                    {progress.includes('example') ? (
                      <CheckCircle2 className="w-6 h-6 text-teal-500" />
                    ) : (
                      <Circle className="w-6 h-6" />
                    )}
                  </button>
                  Complete Example
                </h2>
                <p className="text-muted-foreground leading-relaxed mb-4">
                  Here's a complete end-to-end example putting everything together:
                </p>

                <CodeBlock 
                  filename="complete_batch_pipeline.py"
                  code={`import boto3
import sagemaker
from sagemaker.transformer import Transformer
import pandas as pd
from io import StringIO
from datetime import datetime

# Initialize
sagemaker_session = sagemaker.Session()
bucket = sagemaker_session.default_bucket()
prefix = 'batch-inference-demo'
role = 'arn:aws:iam::YOUR_ACCOUNT:role/SageMakerRole'

# 1. Prepare and upload input data
print("Uploading input data...")
input_data = pd.DataFrame({
    'feature1': range(1000),
    'feature2': [i * 0.1 for i in range(1000)]
})

s3_client = boto3.client('s3')
csv_buffer = StringIO()
input_data.to_csv(csv_buffer, index=False, header=False)
s3_client.put_object(
    Bucket=bucket,
    Key=f'{prefix}/input/data.csv',
    Body=csv_buffer.getvalue()
)

# 2. Create and run batch transform job
print("Starting batch transform job...")
job_name = f"batch-demo-{datetime.now().strftime('%Y%m%d-%H%M%S')}"

transformer = Transformer(
    model_name='my-trained-model',
    instance_count=1,
    instance_type='ml.m5.xlarge',
    output_path=f's3://{bucket}/{prefix}/output/{job_name}',
    sagemaker_session=sagemaker_session,
    strategy='MultiRecord',
    max_payload=6,
    accept='text/csv'
)

transformer.transform(
    data=f's3://{bucket}/{prefix}/input',
    content_type='text/csv',
    split_type='Line',
    join_source='Input',  # Include input in output
    wait=True,
    logs=True
)

# 3. Download and process results
print("Downloading results...")
paginator = s3_client.get_paginator('list_objects_v2')
results = []

for page in paginator.paginate(Bucket=bucket, Prefix=f'{prefix}/output/{job_name}'):
    for obj in page.get('Contents', []):
        response = s3_client.get_object(Bucket=bucket, Key=obj['Key'])
        content = response['Body'].read().decode('utf-8')
        results.append(pd.read_csv(StringIO(content)))

final_results = pd.concat(results, ignore_index=True)
print(f"Processed {len(final_results)} predictions")
print(final_results.head())`}
                />

                <OutputBlock 
                  output={`Uploading input data...
Starting batch transform job...
INFO:sagemaker:Creating transform job with name: batch-demo-20240115-143022
INFO:sagemaker:Transform job completed. Status: Completed
Downloading results...
Processed 1000 predictions
   feature1  feature2  prediction
0         0       0.0       0.123
1         1       0.1       0.156
2         2       0.2       0.189
3         3       0.3       0.221
4         4       0.4       0.254`}
                  title="Output"
                />

                <Callout type="tip" title="Production Ready">
                  This pipeline can be wrapped in a Lambda function and scheduled with EventBridge for 
                  fully automated batch inference!
                </Callout>
              </section>

              {/* Next Steps */}
              <section id="next-steps" className="mb-16">
                <h2 className="text-2xl font-bold text-foreground mb-4 flex items-center gap-3">
                  <button 
                    onClick={() => toggleProgress('next-steps')}
                    className="text-muted-foreground hover:text-teal-500 transition-colors"
                  >
                    {progress.includes('next-steps') ? (
                      <CheckCircle2 className="w-6 h-6 text-teal-500" />
                    ) : (
                      <Circle className="w-6 h-6" />
                    )}
                  </button>
                  Next Steps
                </h2>
                <p className="text-muted-foreground leading-relaxed mb-6">
                  You've learned how to deploy ML models for batch inference on AWS. Here's what to explore next:
                </p>

                <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                  <Link to="/docs/onlinedeployment/aws" className="group p-6 rounded-2xl bg-card/50 border border-border hover:border-foreground/20 hover:shadow-lg hover:shadow-foreground/5 transition-all">
                    <h3 className="font-semibold text-foreground mb-1 group-hover:text-teal-500 transition-colors">
                      Online Deployment on AWS
                    </h3>
                    <p className="text-sm text-muted-foreground">
                      Deploy real-time inference endpoints with SageMaker
                    </p>
                  </Link>

                  <Link to="/docs/batchdeployment/gcp" className="group p-6 rounded-2xl bg-card/50 border border-border hover:border-foreground/20 hover:shadow-lg hover:shadow-foreground/5 transition-all">
                    <h3 className="font-semibold text-foreground mb-1 group-hover:text-teal-500 transition-colors">
                      Batch Deployment on GCP
                    </h3>
                    <p className="text-sm text-muted-foreground">
                      Learn the GCP approach to batch inference
                    </p>
                  </Link>

                  <Link to="/projects/neural-network" className="group p-6 rounded-2xl bg-card/50 border border-border hover:border-foreground/20 hover:shadow-lg hover:shadow-foreground/5 transition-all">
                    <h3 className="font-semibold text-foreground mb-1 group-hover:text-teal-500 transition-colors">
                      Build a Neural Network
                    </h3>
                    <p className="text-sm text-muted-foreground">
                      Create a model from scratch to deploy
                    </p>
                  </Link>

                  <Link to="/docs" className="group p-6 rounded-2xl bg-card/50 border border-border hover:border-foreground/20 hover:shadow-lg hover:shadow-foreground/5 transition-all">
                    <h3 className="font-semibold text-foreground mb-1 group-hover:text-teal-500 transition-colors">
                      Explore More Docs
                    </h3>
                    <p className="text-sm text-muted-foreground">
                      Browse all available documentation
                    </p>
                  </Link>
                </div>
              </section>

              {/* Footer Navigation */}
              <div className="flex items-center justify-between pt-8 border-t border-border">
                <Link to="/docs/model-deployment" className="flex items-center gap-2 text-muted-foreground hover:text-foreground transition-colors">
                  <ArrowLeft className="w-4 h-4" />
                  Back to Model Deployment
                </Link>
                <a 
                  href="https://github.com" 
                  target="_blank" 
                  rel="noopener noreferrer"
                  className="flex items-center gap-2 text-muted-foreground hover:text-foreground transition-colors"
                >
                  Edit on GitHub
                  <ExternalLink className="w-4 h-4" />
                </a>
              </div>
            </article>

            {/* Right Sidebar - On This Page (Desktop) */}
            <aside className="hidden xl:block w-56 shrink-0">
              <div className="sticky top-28">
                <div className="flex items-center gap-2 mb-4">
                  <List className="w-4 h-4 text-muted-foreground" />
                  <span className="text-sm font-medium text-foreground">On this page</span>
                </div>
                <nav className="space-y-1 mb-6">
                  {sections.map((section) => (
                    <button
                      key={section.id}
                      onClick={() => scrollToSection(section.id)}
                      className={`block w-full text-left text-sm py-1.5 transition-colors ${
                        section.parent ? 'pl-4' : ''
                      } ${
                        activeSection === section.id
                          ? 'text-teal-500 font-medium'
                          : 'text-muted-foreground hover:text-foreground'
                      }`}
                    >
                      {section.title}
                    </button>
                  ))}
                </nav>
              </div>
            </aside>
          </div>
        </div>
      </main>
      
      <Footer />
    </div>
  );
};

export default BatchDeploymentAWS;
