import { useState, useEffect, useRef } from 'react';
import { Link } from 'react-router-dom';
import Navbar from '@/components/layout/Navbar';
import Footer from '@/components/layout/Footer';
import { CodeBlock, Callout, OutputBlock, InlineCode } from '@/components/project/CodeBlock';
import { 
  ChevronRight, 
  Clock, 
  Users, 
  Star, 
  GitFork,
  ArrowLeft,
  Github,
  BookOpen,
  List,
  ExternalLink,
  CheckCircle2,
  Circle,
  Download,
  Loader2,
  Globe
} from 'lucide-react';
import { Button } from '@/components/ui/button';

const sections = [
  { id: 'overview', title: 'Overview' },
  { id: 'prerequisites', title: 'Prerequisites' },
  { id: 'setup', title: 'GCP Setup' },
  { id: 'vertex-ai', title: 'Vertex AI Batch Prediction' },
  { id: 'batch-jobs', title: 'Creating Batch Jobs', parent: 'vertex-ai' },
  { id: 'custom-containers', title: 'Custom Containers', parent: 'vertex-ai' },
  { id: 'gcs-integration', title: 'Cloud Storage Integration' },
  { id: 'cloud-functions', title: 'Cloud Functions Triggers' },
  { id: 'cloud-scheduler', title: 'Cloud Scheduler' },
  { id: 'monitoring', title: 'Monitoring & Logging' },
  { id: 'cost-optimization', title: 'Cost Optimization' },
  { id: 'example', title: 'Complete Example' },
  { id: 'next-steps', title: 'Next Steps' },
];

const BatchDeploymentGCP = () => {
  const [activeSection, setActiveSection] = useState('overview');
  const [sidebarOpen, setSidebarOpen] = useState(false);
  const [progress, setProgress] = useState<string[]>([]);
  const [isDownloading, setIsDownloading] = useState(false);
  const contentRef = useRef<HTMLElement>(null);

  const handleDownloadPDF = async () => {
    setIsDownloading(true);
    
    const pdfContent = `
BATCH DEPLOYMENT ON GCP
============================

A Complete Guide to Deploying ML Models for Batch Inference on Google Cloud Platform

Difficulty: Intermediate
Estimated Time: 4 hours

TABLE OF CONTENTS
-----------------
1. Overview
2. Prerequisites
3. GCP Setup
4. Vertex AI Batch Prediction
   - Creating Batch Jobs
   - Custom Containers
5. Cloud Storage Integration
6. Cloud Functions Triggers
7. Cloud Scheduler
8. Monitoring & Logging
9. Cost Optimization
10. Complete Example
11. Next Steps

---
Generated by MLCodex.dev
Batch Deployment on GCP
`;

    const blob = new Blob([pdfContent], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    
    const link = document.createElement('a');
    link.href = url;
    link.download = 'batch-deployment-gcp.txt';
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
    
    setTimeout(() => {
      setIsDownloading(false);
    }, 1000);
  };

  useEffect(() => {
    const handleScroll = () => {
      const sectionElements = sections.map(s => ({
        id: s.id,
        element: document.getElementById(s.id)
      })).filter(s => s.element);

      for (const section of sectionElements.reverse()) {
        if (section.element) {
          const rect = section.element.getBoundingClientRect();
          if (rect.top <= 120) {
            setActiveSection(section.id);
            break;
          }
        }
      }
    };

    window.addEventListener('scroll', handleScroll);
    return () => window.removeEventListener('scroll', handleScroll);
  }, []);

  const scrollToSection = (id: string) => {
    const element = document.getElementById(id);
    if (element) {
      const offset = 100;
      const elementPosition = element.getBoundingClientRect().top + window.scrollY;
      window.scrollTo({ top: elementPosition - offset, behavior: 'smooth' });
    }
  };

  const toggleProgress = (sectionId: string) => {
    setProgress(prev => 
      prev.includes(sectionId) 
        ? prev.filter(id => id !== sectionId)
        : [...prev, sectionId]
    );
  };

  return (
    <div className="min-h-screen bg-background relative">
      <div className="noise-overlay" />
      <Navbar variant="simple" />
      
      <main className="pt-24 pb-20" ref={contentRef}>
        <div className="container mx-auto px-6">
          {/* Breadcrumb */}
          <div className="flex items-center gap-2 text-sm text-muted-foreground mb-8">
            <Link to="/docs" className="hover:text-foreground transition-colors">Docs</Link>
            <ChevronRight className="w-4 h-4" />
            <Link to="/docs/model-deployment" className="hover:text-foreground transition-colors">Model Deployment</Link>
            <ChevronRight className="w-4 h-4" />
            <span className="text-foreground">Batch Deployment - GCP</span>
          </div>

          <div className="flex gap-8 lg:gap-12">
            {/* Left Sidebar */}
            <aside className="hidden lg:block w-64 shrink-0">
              <div className="sticky top-28">
                <div className="flex items-center gap-2 mb-4">
                  <BookOpen className="w-4 h-4 text-muted-foreground" />
                  <span className="text-sm font-medium text-foreground">Related Docs</span>
                </div>
                <nav className="space-y-1">
                  {[
                    { slug: '/docs/batchdeployment/aws', title: 'Batch Deploy on AWS' },
                    { slug: '/docs/onlinedeployment/aws', title: 'Online Deploy on AWS' },
                    { slug: '/docs/onlinedeployment/gcp', title: 'Online Deploy on GCP' },
                  ].map((doc) => (
                    <Link
                      key={doc.slug}
                      to={doc.slug}
                      className="block py-1.5 text-sm text-muted-foreground hover:text-foreground transition-colors"
                    >
                      {doc.title}
                    </Link>
                  ))}
                </nav>

                <Link 
                  to="/docs/model-deployment"
                  className="flex items-center gap-2 mt-4 text-sm text-muted-foreground hover:text-foreground transition-colors"
                >
                  View all deployment docs
                  <ChevronRight className="w-4 h-4" />
                </Link>

                {/* Progress Tracker */}
                <div className="mt-8 pt-6 border-t border-border">
                  <div className="text-sm font-medium text-foreground mb-3">Your Progress</div>
                  <div className="text-xs text-muted-foreground mb-2">
                    {progress.length} / {sections.filter(s => !s.parent).length} sections completed
                  </div>
                  <div className="w-full h-2 rounded-full bg-foreground/10">
                    <div 
                      className="h-full rounded-full bg-gradient-to-r from-teal-500 to-cyan-500 transition-all"
                      style={{ width: `${(progress.length / sections.filter(s => !s.parent).length) * 100}%` }}
                    />
                  </div>
                </div>

                {/* Quick Actions */}
                <div className="mt-6 pt-6 border-t border-border">
                  <div className="text-sm font-medium text-foreground mb-3">Quick Actions</div>
                  <div className="space-y-2">
                    <a 
                      href="https://github.com" 
                      target="_blank" 
                      rel="noopener noreferrer"
                      className="flex items-center gap-2 text-sm text-muted-foreground hover:text-foreground transition-colors py-1"
                    >
                      <Github className="w-4 h-4" />
                      View Source
                    </a>
                    <button 
                      onClick={handleDownloadPDF}
                      disabled={isDownloading}
                      className="flex items-center gap-2 text-sm text-muted-foreground hover:text-foreground transition-colors py-1 disabled:opacity-50"
                    >
                      {isDownloading ? (
                        <Loader2 className="w-4 h-4 animate-spin" />
                      ) : (
                        <Download className="w-4 h-4" />
                      )}
                      {isDownloading ? 'Downloading...' : 'Download PDF'}
                    </button>
                  </div>
                </div>
              </div>
            </aside>

            {/* Main Content */}
            <article className="flex-1 min-w-0 max-w-4xl">
              {/* Header */}
              <header className="mb-12">
                <div className="mb-6">
                  <div className="flex items-center gap-3 mb-4">
                    <div className="w-12 h-12 rounded-xl bg-blue-500/10 border border-blue-500/20 flex items-center justify-center">
                      <Globe className="w-6 h-6 text-blue-400" />
                    </div>
                    <span className="text-[10px] px-2.5 py-1 rounded-full bg-blue-500/10 text-blue-400 border border-blue-500/20 font-medium uppercase tracking-wider">
                      GCP
                    </span>
                  </div>
                  <h1 className="text-4xl lg:text-5xl font-bold tracking-tight mb-4">
                    Batch Deployment on GCP
                  </h1>
                  <p className="text-lg text-muted-foreground leading-relaxed">
                    Deploy ML models for batch inference using Google Cloud's Vertex AI, Cloud Storage, 
                    Cloud Functions, and Cloud Scheduler. Process large datasets at scale.
                  </p>
                </div>

                {/* Meta Info */}
                <div className="flex flex-wrap items-center gap-6 text-sm text-muted-foreground mb-6">
                  <div className="flex items-center gap-1.5">
                    <Clock className="w-4 h-4" />
                    <span>4 hours</span>
                  </div>
                  <div className="flex items-center gap-1.5">
                    <Star className="w-4 h-4" />
                    <span>1,234 stars</span>
                  </div>
                  <div className="flex items-center gap-1.5">
                    <GitFork className="w-4 h-4" />
                    <span>356 forks</span>
                  </div>
                  <div className="flex items-center gap-1.5">
                    <Users className="w-4 h-4" />
                    <span>72 contributors</span>
                  </div>
                  <span className="px-2.5 py-1 rounded-full bg-amber-400/10 text-amber-400 border border-amber-400/20 text-xs font-medium">
                    Intermediate
                  </span>
                </div>

                {/* Action Buttons */}
                <div className="flex flex-wrap gap-3">
                  <Button variant="hero" size="lg">
                    <Github className="w-4 h-4 mr-2" />
                    View on GitHub
                  </Button>
                  <Button 
                    variant="outline" 
                    size="lg" 
                    className="border-foreground/20 hover:bg-foreground/5"
                    onClick={handleDownloadPDF}
                    disabled={isDownloading}
                  >
                    {isDownloading ? (
                      <Loader2 className="w-4 h-4 mr-2 animate-spin" />
                    ) : (
                      <Download className="w-4 h-4 mr-2" />
                    )}
                    {isDownloading ? 'Downloading...' : 'Download PDF'}
                  </Button>
                </div>
              </header>

              {/* Overview Section */}
              <section id="overview" className="mb-16">
                <h2 className="text-2xl font-bold text-foreground mb-4 flex items-center gap-3">
                  <button 
                    onClick={() => toggleProgress('overview')}
                    className="text-muted-foreground hover:text-teal-500 transition-colors"
                  >
                    {progress.includes('overview') ? (
                      <CheckCircle2 className="w-6 h-6 text-teal-500" />
                    ) : (
                      <Circle className="w-6 h-6" />
                    )}
                  </button>
                  Overview
                </h2>
                <p className="text-muted-foreground leading-relaxed mb-4">
                  Google Cloud Platform provides Vertex AI for deploying ML models at scale. For batch inference, 
                  Vertex AI Batch Prediction offers a managed service that handles infrastructure provisioning, 
                  scaling, and job orchestration automatically.
                </p>
                <p className="text-muted-foreground leading-relaxed mb-4">
                  This guide covers everything from setting up your GCP environment to creating production-ready 
                  batch inference pipelines with monitoring and cost optimization.
                </p>

                <div className="grid grid-cols-1 md:grid-cols-3 gap-4 mt-8">
                  <div className="p-4 rounded-xl bg-card/50 border border-border">
                    <div className="text-2xl font-bold text-foreground mb-1">99.9%</div>
                    <div className="text-sm text-muted-foreground">SLA Availability</div>
                  </div>
                  <div className="p-4 rounded-xl bg-card/50 border border-border">
                    <div className="text-2xl font-bold text-foreground mb-1">PB+</div>
                    <div className="text-sm text-muted-foreground">Data Processing</div>
                  </div>
                  <div className="p-4 rounded-xl bg-card/50 border border-border">
                    <div className="text-2xl font-bold text-foreground mb-1">Global</div>
                    <div className="text-sm text-muted-foreground">Multi-Region</div>
                  </div>
                </div>
              </section>

              {/* Prerequisites Section */}
              <section id="prerequisites" className="mb-16">
                <h2 className="text-2xl font-bold text-foreground mb-4 flex items-center gap-3">
                  <button 
                    onClick={() => toggleProgress('prerequisites')}
                    className="text-muted-foreground hover:text-teal-500 transition-colors"
                  >
                    {progress.includes('prerequisites') ? (
                      <CheckCircle2 className="w-6 h-6 text-teal-500" />
                    ) : (
                      <Circle className="w-6 h-6" />
                    )}
                  </button>
                  Prerequisites
                </h2>
                <p className="text-muted-foreground leading-relaxed mb-4">
                  Before starting this guide, ensure you have:
                </p>
                <ul className="space-y-3 text-muted-foreground">
                  <li className="flex items-start gap-3">
                    <ChevronRight className="w-5 h-5 text-teal-500 shrink-0 mt-0.5" />
                    <span><strong className="text-foreground">GCP Account</strong> — With billing enabled and appropriate permissions</span>
                  </li>
                  <li className="flex items-start gap-3">
                    <ChevronRight className="w-5 h-5 text-teal-500 shrink-0 mt-0.5" />
                    <span><strong className="text-foreground">gcloud CLI</strong> — Installed and authenticated with your project</span>
                  </li>
                  <li className="flex items-start gap-3">
                    <ChevronRight className="w-5 h-5 text-teal-500 shrink-0 mt-0.5" />
                    <span><strong className="text-foreground">Python 3.8+</strong> — With google-cloud-aiplatform SDK installed</span>
                  </li>
                  <li className="flex items-start gap-3">
                    <ChevronRight className="w-5 h-5 text-teal-500 shrink-0 mt-0.5" />
                    <span><strong className="text-foreground">Trained ML Model</strong> — A model ready for deployment</span>
                  </li>
                </ul>

                <Callout type="tip" title="Free Credits">
                  New GCP users get $300 in free credits to explore all services, including Vertex AI. 
                  This is plenty to complete this tutorial!
                </Callout>
              </section>

              {/* Setup Section */}
              <section id="setup" className="mb-16">
                <h2 className="text-2xl font-bold text-foreground mb-4 flex items-center gap-3">
                  <button 
                    onClick={() => toggleProgress('setup')}
                    className="text-muted-foreground hover:text-teal-500 transition-colors"
                  >
                    {progress.includes('setup') ? (
                      <CheckCircle2 className="w-6 h-6 text-teal-500" />
                    ) : (
                      <Circle className="w-6 h-6" />
                    )}
                  </button>
                  GCP Setup
                </h2>
                <p className="text-muted-foreground leading-relaxed mb-4">
                  Let's set up your GCP environment and install the required Python packages.
                </p>

                <CodeBlock 
                  language="bash"
                  filename="terminal"
                  code={`# Install required packages
pip install google-cloud-aiplatform google-cloud-storage pandas

# Authenticate with GCP
gcloud auth application-default login

# Set your project
gcloud config set project YOUR_PROJECT_ID

# Enable required APIs
gcloud services enable aiplatform.googleapis.com
gcloud services enable storage.googleapis.com
gcloud services enable cloudfunctions.googleapis.com
gcloud services enable cloudscheduler.googleapis.com`}
                  showLineNumbers={false}
                />

                <p className="text-muted-foreground leading-relaxed my-4">
                  Initialize the Vertex AI SDK in Python:
                </p>

                <CodeBlock 
                  filename="setup.py"
                  code={`from google.cloud import aiplatform
from google.cloud import storage

# Initialize Vertex AI
PROJECT_ID = "your-project-id"
REGION = "us-central1"
BUCKET_NAME = f"{PROJECT_ID}-batch-inference"

aiplatform.init(
    project=PROJECT_ID,
    location=REGION,
    staging_bucket=f"gs://{BUCKET_NAME}"
)

# Create a GCS bucket for data
storage_client = storage.Client()
try:
    bucket = storage_client.create_bucket(BUCKET_NAME, location=REGION)
    print(f"Created bucket: {bucket.name}")
except Exception as e:
    print(f"Bucket exists or error: {e}")

print(f"Project: {PROJECT_ID}")
print(f"Region: {REGION}")
print(f"Bucket: gs://{BUCKET_NAME}")`}
                />

                <Callout type="info" title="Service Account">
                  For production deployments, use a dedicated service account with minimal required permissions 
                  instead of your personal credentials.
                </Callout>
              </section>

              {/* Vertex AI Section */}
              <section id="vertex-ai" className="mb-16">
                <h2 className="text-2xl font-bold text-foreground mb-4 flex items-center gap-3">
                  <button 
                    onClick={() => toggleProgress('vertex-ai')}
                    className="text-muted-foreground hover:text-teal-500 transition-colors"
                  >
                    {progress.includes('vertex-ai') ? (
                      <CheckCircle2 className="w-6 h-6 text-teal-500" />
                    ) : (
                      <Circle className="w-6 h-6" />
                    )}
                  </button>
                  Vertex AI Batch Prediction
                </h2>
                <p className="text-muted-foreground leading-relaxed mb-8">
                  Vertex AI Batch Prediction allows you to run inference on large datasets efficiently 
                  without managing infrastructure.
                </p>

                {/* Batch Jobs */}
                <div id="batch-jobs" className="mb-12">
                  <h3 className="text-xl font-semibold text-foreground mb-4">Creating Batch Jobs</h3>
                  <p className="text-muted-foreground leading-relaxed mb-4">
                    First, upload your model to Vertex AI, then create batch prediction jobs:
                  </p>

                  <CodeBlock 
                    filename="batch_prediction.py"
                    code={`from google.cloud import aiplatform

# Upload model to Vertex AI Model Registry
model = aiplatform.Model.upload(
    display_name="my-batch-model",
    artifact_uri="gs://your-bucket/model-artifacts/",
    serving_container_image_uri="us-docker.pkg.dev/vertex-ai/prediction/sklearn-cpu.1-0:latest",
)

print(f"Model resource name: {model.resource_name}")

# Create a batch prediction job
batch_prediction_job = model.batch_predict(
    job_display_name="batch-prediction-job",
    gcs_source="gs://your-bucket/input-data/",
    gcs_destination_prefix="gs://your-bucket/predictions/",
    machine_type="n1-standard-4",
    accelerator_count=0,
    accelerator_type=None,
    starting_replica_count=2,
    max_replica_count=10,
    sync=False  # Run asynchronously
)

print(f"Job resource name: {batch_prediction_job.resource_name}")
print(f"Job state: {batch_prediction_job.state}")`}
                  />

                  <div className="grid grid-cols-1 md:grid-cols-2 gap-4 mt-6">
                    <div className="p-4 rounded-xl bg-blue-500/10 border border-blue-500/20">
                      <div className="font-semibold text-blue-400 mb-1">Auto-Scaling</div>
                      <div className="text-sm text-muted-foreground">Automatically scales between min and max replicas</div>
                    </div>
                    <div className="p-4 rounded-xl bg-purple-500/10 border border-purple-500/20">
                      <div className="font-semibold text-purple-400 mb-1">Multiple Formats</div>
                      <div className="text-sm text-muted-foreground">Supports JSONL, CSV, TFRecord, and BigQuery</div>
                    </div>
                  </div>
                </div>

                {/* Custom Containers */}
                <div id="custom-containers" className="mb-12">
                  <h3 className="text-xl font-semibold text-foreground mb-4">Custom Containers</h3>
                  <p className="text-muted-foreground leading-relaxed mb-4">
                    For custom models, create a Docker container and push it to Artifact Registry:
                  </p>

                  <CodeBlock 
                    filename="Dockerfile"
                    code={`FROM python:3.9-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY model/ ./model/
COPY serve.py .

ENV AIP_STORAGE_URI=/gcs/model
ENV AIP_HTTP_PORT=8080

EXPOSE 8080

CMD ["python", "serve.py"]`}
                  />

                  <CodeBlock 
                    filename="serve.py"
                    code={`from flask import Flask, request, jsonify
import joblib
import os

app = Flask(__name__)

# Load model at startup
model_path = os.environ.get('AIP_STORAGE_URI', './model')
model = joblib.load(f'{model_path}/model.joblib')

@app.route('/predict', methods=['POST'])
def predict():
    instances = request.json.get('instances', [])
    predictions = model.predict(instances)
    return jsonify({'predictions': predictions.tolist()})

@app.route('/health', methods=['GET'])
def health():
    return 'OK', 200

if __name__ == '__main__':
    app.run(host='0.0.0.0', port=int(os.environ.get('AIP_HTTP_PORT', 8080)))`}
                  />
                </div>
              </section>

              {/* Cloud Storage Integration */}
              <section id="gcs-integration" className="mb-16">
                <h2 className="text-2xl font-bold text-foreground mb-4 flex items-center gap-3">
                  <button 
                    onClick={() => toggleProgress('gcs-integration')}
                    className="text-muted-foreground hover:text-teal-500 transition-colors"
                  >
                    {progress.includes('gcs-integration') ? (
                      <CheckCircle2 className="w-6 h-6 text-teal-500" />
                    ) : (
                      <Circle className="w-6 h-6" />
                    )}
                  </button>
                  Cloud Storage Integration
                </h2>
                <p className="text-muted-foreground leading-relaxed mb-4">
                  Google Cloud Storage serves as the data layer for batch predictions:
                </p>

                <CodeBlock 
                  filename="gcs_utils.py"
                  code={`from google.cloud import storage
import pandas as pd
import json

def upload_batch_data(bucket_name: str, data: pd.DataFrame, destination: str):
    """Upload data to GCS in JSONL format for batch prediction."""
    storage_client = storage.Client()
    bucket = storage_client.bucket(bucket_name)
    blob = bucket.blob(destination)
    
    # Convert to JSONL format (required by Vertex AI)
    jsonl_data = data.to_json(orient='records', lines=True)
    blob.upload_from_string(jsonl_data)
    
    print(f"Uploaded to gs://{bucket_name}/{destination}")
    return f"gs://{bucket_name}/{destination}"

def download_predictions(bucket_name: str, prefix: str) -> pd.DataFrame:
    """Download prediction results from GCS."""
    storage_client = storage.Client()
    bucket = storage_client.bucket(bucket_name)
    
    blobs = bucket.list_blobs(prefix=prefix)
    
    all_predictions = []
    for blob in blobs:
        if blob.name.endswith('.jsonl'):
            content = blob.download_as_string().decode('utf-8')
            for line in content.strip().split('\\n'):
                all_predictions.append(json.loads(line))
    
    return pd.DataFrame(all_predictions)

# Example usage
input_data = pd.DataFrame({
    'feature1': [1.0, 2.0, 3.0, 4.0, 5.0],
    'feature2': [0.1, 0.2, 0.3, 0.4, 0.5]
})

upload_batch_data(BUCKET_NAME, input_data, 'input/batch_data.jsonl')`}
                />
              </section>

              {/* Cloud Functions Section */}
              <section id="cloud-functions" className="mb-16">
                <h2 className="text-2xl font-bold text-foreground mb-4 flex items-center gap-3">
                  <button 
                    onClick={() => toggleProgress('cloud-functions')}
                    className="text-muted-foreground hover:text-teal-500 transition-colors"
                  >
                    {progress.includes('cloud-functions') ? (
                      <CheckCircle2 className="w-6 h-6 text-teal-500" />
                    ) : (
                      <Circle className="w-6 h-6" />
                    )}
                  </button>
                  Cloud Functions Triggers
                </h2>
                <p className="text-muted-foreground leading-relaxed mb-4">
                  Trigger batch jobs automatically when new data arrives in Cloud Storage:
                </p>

                <CodeBlock 
                  filename="main.py"
                  code={`import functions_framework
from google.cloud import aiplatform

PROJECT_ID = "your-project-id"
REGION = "us-central1"
MODEL_ID = "your-model-id"

@functions_framework.cloud_event
def trigger_batch_prediction(cloud_event):
    """Triggered by a Cloud Storage event."""
    
    data = cloud_event.data
    bucket = data["bucket"]
    name = data["name"]
    
    # Only process files in the input folder
    if not name.startswith("input/"):
        print(f"Skipping file: {name}")
        return
    
    print(f"Processing file: gs://{bucket}/{name}")
    
    # Initialize Vertex AI
    aiplatform.init(project=PROJECT_ID, location=REGION)
    
    # Get the model
    model = aiplatform.Model(model_name=MODEL_ID)
    
    # Create batch prediction job
    job = model.batch_predict(
        job_display_name=f"batch-{name.replace('/', '-')}",
        gcs_source=f"gs://{bucket}/{name}",
        gcs_destination_prefix=f"gs://{bucket}/predictions/",
        machine_type="n1-standard-4",
        starting_replica_count=1,
        max_replica_count=5,
        sync=False
    )
    
    print(f"Started batch prediction job: {job.resource_name}")
    return "OK"`}
                />

                <p className="text-muted-foreground leading-relaxed my-4">
                  Deploy the Cloud Function:
                </p>

                <CodeBlock 
                  language="bash"
                  filename="terminal"
                  code={`gcloud functions deploy trigger-batch-prediction \\
  --gen2 \\
  --runtime=python311 \\
  --region=us-central1 \\
  --source=. \\
  --entry-point=trigger_batch_prediction \\
  --trigger-event-filters="type=google.cloud.storage.object.v1.finalized" \\
  --trigger-event-filters="bucket=your-bucket-name"`}
                  showLineNumbers={false}
                />
              </section>

              {/* Cloud Scheduler Section */}
              <section id="cloud-scheduler" className="mb-16">
                <h2 className="text-2xl font-bold text-foreground mb-4 flex items-center gap-3">
                  <button 
                    onClick={() => toggleProgress('cloud-scheduler')}
                    className="text-muted-foreground hover:text-teal-500 transition-colors"
                  >
                    {progress.includes('cloud-scheduler') ? (
                      <CheckCircle2 className="w-6 h-6 text-teal-500" />
                    ) : (
                      <Circle className="w-6 h-6" />
                    )}
                  </button>
                  Cloud Scheduler
                </h2>
                <p className="text-muted-foreground leading-relaxed mb-4">
                  Schedule batch jobs to run at specific times:
                </p>

                <CodeBlock 
                  language="bash"
                  filename="terminal"
                  code={`# Create a Cloud Scheduler job that triggers daily at midnight
gcloud scheduler jobs create http daily-batch-inference \\
  --schedule="0 0 * * *" \\
  --uri="https://REGION-PROJECT_ID.cloudfunctions.net/trigger-batch-prediction" \\
  --http-method=POST \\
  --message-body='{"source": "scheduler", "input_path": "input/daily/"}' \\
  --time-zone="UTC" \\
  --oidc-service-account-email="your-service-account@PROJECT_ID.iam.gserviceaccount.com"`}
                  showLineNumbers={false}
                />

                <Callout type="info" title="Cron Syntax">
                  Cloud Scheduler uses standard cron syntax. <InlineCode>0 0 * * *</InlineCode> means 
                  "at midnight every day". Use <InlineCode>0 */6 * * *</InlineCode> for every 6 hours.
                </Callout>
              </section>

              {/* Monitoring Section */}
              <section id="monitoring" className="mb-16">
                <h2 className="text-2xl font-bold text-foreground mb-4 flex items-center gap-3">
                  <button 
                    onClick={() => toggleProgress('monitoring')}
                    className="text-muted-foreground hover:text-teal-500 transition-colors"
                  >
                    {progress.includes('monitoring') ? (
                      <CheckCircle2 className="w-6 h-6 text-teal-500" />
                    ) : (
                      <Circle className="w-6 h-6" />
                    )}
                  </button>
                  Monitoring & Logging
                </h2>
                <p className="text-muted-foreground leading-relaxed mb-4">
                  Monitor batch jobs using Cloud Monitoring and Logging:
                </p>

                <CodeBlock 
                  filename="monitoring.py"
                  code={`from google.cloud import aiplatform
from google.cloud import monitoring_v3
from datetime import datetime, timedelta

def get_job_status(job_name: str):
    """Get the status of a batch prediction job."""
    job = aiplatform.BatchPredictionJob(batch_prediction_job_name=job_name)
    
    print(f"Job: {job.display_name}")
    print(f"State: {job.state.name}")
    print(f"Create time: {job.create_time}")
    
    if job.state.name == "JOB_STATE_SUCCEEDED":
        print(f"Completion time: {job.update_time}")
        print(f"Output: {job.output_info.gcs_output_directory}")
    elif job.state.name == "JOB_STATE_FAILED":
        print(f"Error: {job.error}")
    
    return job

def list_recent_jobs(hours: int = 24):
    """List all batch prediction jobs from the past N hours."""
    jobs = aiplatform.BatchPredictionJob.list(
        filter=f'create_time>"{(datetime.utcnow() - timedelta(hours=hours)).isoformat()}Z"',
        order_by="create_time desc"
    )
    
    for job in jobs:
        print(f"{job.display_name}: {job.state.name}")
    
    return jobs

def create_alert_policy(project_id: str):
    """Create an alert for failed batch prediction jobs."""
    client = monitoring_v3.AlertPolicyServiceClient()
    
    policy = monitoring_v3.AlertPolicy(
        display_name="Batch Prediction Job Failures",
        conditions=[
            monitoring_v3.AlertPolicy.Condition(
                display_name="Job Failed",
                condition_threshold=monitoring_v3.AlertPolicy.Condition.MetricThreshold(
                    filter='resource.type="aiplatform.googleapis.com/BatchPredictionJob" AND metric.type="aiplatform.googleapis.com/prediction/batch/job_count" AND metric.labels.state="FAILED"',
                    comparison=monitoring_v3.ComparisonType.COMPARISON_GT,
                    threshold_value=0,
                    duration={"seconds": 0},
                    aggregations=[{
                        "alignment_period": {"seconds": 300},
                        "per_series_aligner": monitoring_v3.Aggregation.Aligner.ALIGN_COUNT
                    }]
                )
            )
        ],
        notification_channels=["projects/PROJECT_ID/notificationChannels/CHANNEL_ID"]
    )
    
    return client.create_alert_policy(name=f"projects/{project_id}", alert_policy=policy)`}
                />
              </section>

              {/* Cost Optimization Section */}
              <section id="cost-optimization" className="mb-16">
                <h2 className="text-2xl font-bold text-foreground mb-4 flex items-center gap-3">
                  <button 
                    onClick={() => toggleProgress('cost-optimization')}
                    className="text-muted-foreground hover:text-teal-500 transition-colors"
                  >
                    {progress.includes('cost-optimization') ? (
                      <CheckCircle2 className="w-6 h-6 text-teal-500" />
                    ) : (
                      <Circle className="w-6 h-6" />
                    )}
                  </button>
                  Cost Optimization
                </h2>
                <p className="text-muted-foreground leading-relaxed mb-4">
                  Optimize costs for batch inference on GCP:
                </p>

                <div className="space-y-4 mb-6">
                  <div className="p-4 rounded-xl bg-card/50 border border-border">
                    <h4 className="font-semibold text-foreground mb-2">Use Preemptible VMs</h4>
                    <p className="text-sm text-muted-foreground mb-3">
                      Preemptible VMs cost up to 80% less than regular VMs for batch workloads.
                    </p>
                    <CodeBlock 
                      filename="preemptible.py"
                      code={`batch_prediction_job = model.batch_predict(
    job_display_name="batch-job-preemptible",
    gcs_source="gs://bucket/input/",
    gcs_destination_prefix="gs://bucket/output/",
    machine_type="n1-standard-4",
    # Enable preemptible instances
    service_account="sa@project.iam.gserviceaccount.com"
)`}
                    />
                  </div>

                  <div className="p-4 rounded-xl bg-card/50 border border-border">
                    <h4 className="font-semibold text-foreground mb-2">Choose the Right Machine Type</h4>
                    <p className="text-sm text-muted-foreground">
                      Start with <InlineCode>n1-standard-2</InlineCode> and scale up based on actual resource usage. 
                      Use custom machine types for optimal price-performance.
                    </p>
                  </div>

                  <div className="p-4 rounded-xl bg-card/50 border border-border">
                    <h4 className="font-semibold text-foreground mb-2">Batch Your Requests</h4>
                    <p className="text-sm text-muted-foreground">
                      Combine multiple small inference requests into larger batches. This reduces startup 
                      overhead and improves throughput.
                    </p>
                  </div>

                  <div className="p-4 rounded-xl bg-card/50 border border-border">
                    <h4 className="font-semibold text-foreground mb-2">Use Regional Resources</h4>
                    <p className="text-sm text-muted-foreground">
                      Keep your data, models, and compute in the same region to avoid egress costs.
                    </p>
                  </div>
                </div>
              </section>

              {/* Complete Example Section */}
              <section id="example" className="mb-16">
                <h2 className="text-2xl font-bold text-foreground mb-4 flex items-center gap-3">
                  <button 
                    onClick={() => toggleProgress('example')}
                    className="text-muted-foreground hover:text-teal-500 transition-colors"
                  >
                    {progress.includes('example') ? (
                      <CheckCircle2 className="w-6 h-6 text-teal-500" />
                    ) : (
                      <Circle className="w-6 h-6" />
                    )}
                  </button>
                  Complete Example
                </h2>
                <p className="text-muted-foreground leading-relaxed mb-4">
                  Here's a complete end-to-end example:
                </p>

                <CodeBlock 
                  filename="complete_gcp_batch.py"
                  code={`from google.cloud import aiplatform
from google.cloud import storage
import pandas as pd
import json
import time

# Configuration
PROJECT_ID = "your-project-id"
REGION = "us-central1"
BUCKET_NAME = f"{PROJECT_ID}-batch-demo"

# Initialize
aiplatform.init(project=PROJECT_ID, location=REGION)
storage_client = storage.Client()

# 1. Prepare input data
print("Preparing input data...")
input_data = pd.DataFrame({
    'feature1': [float(i) for i in range(100)],
    'feature2': [i * 0.1 for i in range(100)]
})

# Upload to GCS in JSONL format
bucket = storage_client.bucket(BUCKET_NAME)
blob = bucket.blob('input/batch_data.jsonl')
jsonl_data = input_data.to_json(orient='records', lines=True)
blob.upload_from_string(jsonl_data)
print(f"Uploaded to gs://{BUCKET_NAME}/input/batch_data.jsonl")

# 2. Get or upload model
print("\\nLoading model...")
models = aiplatform.Model.list(filter='display_name="my-batch-model"')
if models:
    model = models[0]
else:
    model = aiplatform.Model.upload(
        display_name="my-batch-model",
        artifact_uri="gs://your-bucket/model/",
        serving_container_image_uri="us-docker.pkg.dev/vertex-ai/prediction/sklearn-cpu.1-0:latest",
    )
print(f"Using model: {model.display_name}")

# 3. Create batch prediction job
print("\\nStarting batch prediction job...")
job = model.batch_predict(
    job_display_name=f"batch-demo-{int(time.time())}",
    gcs_source=f"gs://{BUCKET_NAME}/input/",
    gcs_destination_prefix=f"gs://{BUCKET_NAME}/predictions/",
    machine_type="n1-standard-4",
    starting_replica_count=1,
    max_replica_count=3,
    sync=True  # Wait for completion
)

print(f"Job completed with state: {job.state.name}")

# 4. Download results
print("\\nDownloading predictions...")
output_blobs = bucket.list_blobs(prefix="predictions/")
results = []
for blob in output_blobs:
    if 'prediction' in blob.name:
        content = blob.download_as_string().decode('utf-8')
        for line in content.strip().split('\\n'):
            if line:
                results.append(json.loads(line))

predictions_df = pd.DataFrame(results)
print(f"\\nProcessed {len(predictions_df)} predictions")
print(predictions_df.head())`}
                />

                <OutputBlock 
                  output={`Preparing input data...
Uploaded to gs://your-project-batch-demo/input/batch_data.jsonl

Loading model...
Using model: my-batch-model

Starting batch prediction job...
Job completed with state: JOB_STATE_SUCCEEDED

Downloading predictions...

Processed 100 predictions
   instance                    prediction
0  {"feature1": 0.0, ...}      0.123
1  {"feature1": 1.0, ...}      0.156
2  {"feature1": 2.0, ...}      0.189
3  {"feature1": 3.0, ...}      0.221
4  {"feature1": 4.0, ...}      0.254`}
                  title="Output"
                />
              </section>

              {/* Next Steps */}
              <section id="next-steps" className="mb-16">
                <h2 className="text-2xl font-bold text-foreground mb-4 flex items-center gap-3">
                  <button 
                    onClick={() => toggleProgress('next-steps')}
                    className="text-muted-foreground hover:text-teal-500 transition-colors"
                  >
                    {progress.includes('next-steps') ? (
                      <CheckCircle2 className="w-6 h-6 text-teal-500" />
                    ) : (
                      <Circle className="w-6 h-6" />
                    )}
                  </button>
                  Next Steps
                </h2>
                <p className="text-muted-foreground leading-relaxed mb-6">
                  You've learned how to deploy ML models for batch inference on GCP. Continue learning:
                </p>

                <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                  <Link to="/docs/onlinedeployment/gcp" className="group p-6 rounded-2xl bg-card/50 border border-border hover:border-foreground/20 hover:shadow-lg hover:shadow-foreground/5 transition-all">
                    <h3 className="font-semibold text-foreground mb-1 group-hover:text-teal-500 transition-colors">
                      Online Deployment on GCP
                    </h3>
                    <p className="text-sm text-muted-foreground">
                      Deploy real-time inference endpoints with Vertex AI
                    </p>
                  </Link>

                  <Link to="/docs/batchdeployment/aws" className="group p-6 rounded-2xl bg-card/50 border border-border hover:border-foreground/20 hover:shadow-lg hover:shadow-foreground/5 transition-all">
                    <h3 className="font-semibold text-foreground mb-1 group-hover:text-teal-500 transition-colors">
                      Batch Deployment on AWS
                    </h3>
                    <p className="text-sm text-muted-foreground">
                      Compare with the AWS approach to batch inference
                    </p>
                  </Link>

                  <Link to="/projects/neural-network" className="group p-6 rounded-2xl bg-card/50 border border-border hover:border-foreground/20 hover:shadow-lg hover:shadow-foreground/5 transition-all">
                    <h3 className="font-semibold text-foreground mb-1 group-hover:text-teal-500 transition-colors">
                      Build a Neural Network
                    </h3>
                    <p className="text-sm text-muted-foreground">
                      Create a model from scratch to deploy
                    </p>
                  </Link>

                  <Link to="/docs" className="group p-6 rounded-2xl bg-card/50 border border-border hover:border-foreground/20 hover:shadow-lg hover:shadow-foreground/5 transition-all">
                    <h3 className="font-semibold text-foreground mb-1 group-hover:text-teal-500 transition-colors">
                      Explore More Docs
                    </h3>
                    <p className="text-sm text-muted-foreground">
                      Browse all available documentation
                    </p>
                  </Link>
                </div>
              </section>

              {/* Footer Navigation */}
              <div className="flex items-center justify-between pt-8 border-t border-border">
                <Link to="/docs/model-deployment" className="flex items-center gap-2 text-muted-foreground hover:text-foreground transition-colors">
                  <ArrowLeft className="w-4 h-4" />
                  Back to Model Deployment
                </Link>
                <a 
                  href="https://github.com" 
                  target="_blank" 
                  rel="noopener noreferrer"
                  className="flex items-center gap-2 text-muted-foreground hover:text-foreground transition-colors"
                >
                  Edit on GitHub
                  <ExternalLink className="w-4 h-4" />
                </a>
              </div>
            </article>

            {/* Right Sidebar - On This Page */}
            <aside className="hidden xl:block w-56 shrink-0">
              <div className="sticky top-28">
                <div className="flex items-center gap-2 mb-4">
                  <List className="w-4 h-4 text-muted-foreground" />
                  <span className="text-sm font-medium text-foreground">On this page</span>
                </div>
                <nav className="space-y-1 mb-6">
                  {sections.map((section) => (
                    <button
                      key={section.id}
                      onClick={() => scrollToSection(section.id)}
                      className={`block w-full text-left text-sm py-1.5 transition-colors ${
                        section.parent ? 'pl-4' : ''
                      } ${
                        activeSection === section.id
                          ? 'text-teal-500 font-medium'
                          : 'text-muted-foreground hover:text-foreground'
                      }`}
                    >
                      {section.title}
                    </button>
                  ))}
                </nav>
              </div>
            </aside>
          </div>
        </div>
      </main>
      
      <Footer />
    </div>
  );
};

export default BatchDeploymentGCP;
