import { useState, useEffect, useRef } from 'react';
import { Link } from 'react-router-dom';
import Navbar from '@/components/layout/Navbar';
import Footer from '@/components/layout/Footer';
import { CodeBlock, Callout, OutputBlock, InlineCode } from '@/components/project/CodeBlock';
import { 
  ChevronRight, 
  Clock, 
  Users, 
  Star, 
  GitFork,
  ArrowLeft,
  Github,
  BookOpen,
  List,
  ExternalLink,
  CheckCircle2,
  Circle,
  Download,
  Loader2,
  Cloud
} from 'lucide-react';
import { Button } from '@/components/ui/button';

const sections = [
  { id: 'overview', title: 'Overview' },
  { id: 'prerequisites', title: 'Prerequisites' },
  { id: 'setup', title: 'AWS Setup' },
  { id: 'sagemaker-endpoints', title: 'SageMaker Endpoints' },
  { id: 'real-time-inference', title: 'Real-Time Inference', parent: 'sagemaker-endpoints' },
  { id: 'multi-model-endpoints', title: 'Multi-Model Endpoints', parent: 'sagemaker-endpoints' },
  { id: 'api-gateway', title: 'API Gateway Integration' },
  { id: 'auto-scaling', title: 'Auto Scaling' },
  { id: 'load-testing', title: 'Load Testing' },
  { id: 'monitoring', title: 'Monitoring & Alerts' },
  { id: 'security', title: 'Security Best Practices' },
  { id: 'example', title: 'Complete Example' },
  { id: 'next-steps', title: 'Next Steps' },
];

const OnlineDeploymentAWS = () => {
  const [activeSection, setActiveSection] = useState('overview');
  const [sidebarOpen, setSidebarOpen] = useState(false);
  const [progress, setProgress] = useState<string[]>([]);
  const [isDownloading, setIsDownloading] = useState(false);
  const contentRef = useRef<HTMLElement>(null);

  const handleDownloadPDF = async () => {
    setIsDownloading(true);
    
    const pdfContent = `
ONLINE DEPLOYMENT ON AWS
============================

A Complete Guide to Deploying ML Models for Real-Time Inference on AWS

Difficulty: Intermediate
Estimated Time: 5 hours

TABLE OF CONTENTS
-----------------
1. Overview
2. Prerequisites
3. AWS Setup
4. SageMaker Endpoints
   - Real-Time Inference
   - Multi-Model Endpoints
5. API Gateway Integration
6. Auto Scaling
7. Load Testing
8. Monitoring & Alerts
9. Security Best Practices
10. Complete Example
11. Next Steps

---
Generated by MLCodex.dev
Online Deployment on AWS
`;

    const blob = new Blob([pdfContent], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    
    const link = document.createElement('a');
    link.href = url;
    link.download = 'online-deployment-aws.txt';
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
    
    setTimeout(() => {
      setIsDownloading(false);
    }, 1000);
  };

  useEffect(() => {
    const handleScroll = () => {
      const sectionElements = sections.map(s => ({
        id: s.id,
        element: document.getElementById(s.id)
      })).filter(s => s.element);

      for (const section of sectionElements.reverse()) {
        if (section.element) {
          const rect = section.element.getBoundingClientRect();
          if (rect.top <= 120) {
            setActiveSection(section.id);
            break;
          }
        }
      }
    };

    window.addEventListener('scroll', handleScroll);
    return () => window.removeEventListener('scroll', handleScroll);
  }, []);

  const scrollToSection = (id: string) => {
    const element = document.getElementById(id);
    if (element) {
      const offset = 100;
      const elementPosition = element.getBoundingClientRect().top + window.scrollY;
      window.scrollTo({ top: elementPosition - offset, behavior: 'smooth' });
    }
  };

  const toggleProgress = (sectionId: string) => {
    setProgress(prev => 
      prev.includes(sectionId) 
        ? prev.filter(id => id !== sectionId)
        : [...prev, sectionId]
    );
  };

  return (
    <div className="min-h-screen bg-background relative">
      <div className="noise-overlay" />
      <Navbar variant="simple" />
      
      <main className="pt-24 pb-20" ref={contentRef}>
        <div className="container mx-auto px-6">
          {/* Breadcrumb */}
          <div className="flex items-center gap-2 text-sm text-muted-foreground mb-8">
            <Link to="/docs" className="hover:text-foreground transition-colors">Docs</Link>
            <ChevronRight className="w-4 h-4" />
            <Link to="/docs/model-deployment" className="hover:text-foreground transition-colors">Model Deployment</Link>
            <ChevronRight className="w-4 h-4" />
            <span className="text-foreground">Online Deployment - AWS</span>
          </div>

          <div className="flex gap-8 lg:gap-12">
            {/* Left Sidebar */}
            <aside className="hidden lg:block w-64 shrink-0">
              <div className="sticky top-28">
                <div className="flex items-center gap-2 mb-4">
                  <BookOpen className="w-4 h-4 text-muted-foreground" />
                  <span className="text-sm font-medium text-foreground">Related Docs</span>
                </div>
                <nav className="space-y-1">
                  {[
                    { slug: '/docs/onlinedeployment/gcp', title: 'Online Deploy on GCP' },
                    { slug: '/docs/batchdeployment/aws', title: 'Batch Deploy on AWS' },
                    { slug: '/docs/batchdeployment/gcp', title: 'Batch Deploy on GCP' },
                  ].map((doc) => (
                    <Link
                      key={doc.slug}
                      to={doc.slug}
                      className="block py-1.5 text-sm text-muted-foreground hover:text-foreground transition-colors"
                    >
                      {doc.title}
                    </Link>
                  ))}
                </nav>

                <Link 
                  to="/docs/model-deployment"
                  className="flex items-center gap-2 mt-4 text-sm text-muted-foreground hover:text-foreground transition-colors"
                >
                  View all deployment docs
                  <ChevronRight className="w-4 h-4" />
                </Link>

                {/* Progress Tracker */}
                <div className="mt-8 pt-6 border-t border-border">
                  <div className="text-sm font-medium text-foreground mb-3">Your Progress</div>
                  <div className="text-xs text-muted-foreground mb-2">
                    {progress.length} / {sections.filter(s => !s.parent).length} sections completed
                  </div>
                  <div className="w-full h-2 rounded-full bg-foreground/10">
                    <div 
                      className="h-full rounded-full bg-gradient-to-r from-teal-500 to-cyan-500 transition-all"
                      style={{ width: `${(progress.length / sections.filter(s => !s.parent).length) * 100}%` }}
                    />
                  </div>
                </div>

                {/* Quick Actions */}
                <div className="mt-6 pt-6 border-t border-border">
                  <div className="text-sm font-medium text-foreground mb-3">Quick Actions</div>
                  <div className="space-y-2">
                    <a 
                      href="https://github.com" 
                      target="_blank" 
                      rel="noopener noreferrer"
                      className="flex items-center gap-2 text-sm text-muted-foreground hover:text-foreground transition-colors py-1"
                    >
                      <Github className="w-4 h-4" />
                      View Source
                    </a>
                    <button 
                      onClick={handleDownloadPDF}
                      disabled={isDownloading}
                      className="flex items-center gap-2 text-sm text-muted-foreground hover:text-foreground transition-colors py-1 disabled:opacity-50"
                    >
                      {isDownloading ? (
                        <Loader2 className="w-4 h-4 animate-spin" />
                      ) : (
                        <Download className="w-4 h-4" />
                      )}
                      {isDownloading ? 'Downloading...' : 'Download PDF'}
                    </button>
                  </div>
                </div>
              </div>
            </aside>

            {/* Main Content */}
            <article className="flex-1 min-w-0 max-w-4xl">
              {/* Header */}
              <header className="mb-12">
                <div className="mb-6">
                  <div className="flex items-center gap-3 mb-4">
                    <div className="w-12 h-12 rounded-xl bg-orange-500/10 border border-orange-500/20 flex items-center justify-center">
                      <Cloud className="w-6 h-6 text-orange-400" />
                    </div>
                    <span className="text-[10px] px-2.5 py-1 rounded-full bg-orange-500/10 text-orange-400 border border-orange-500/20 font-medium uppercase tracking-wider">
                      AWS
                    </span>
                  </div>
                  <h1 className="text-4xl lg:text-5xl font-bold tracking-tight mb-4">
                    Online Deployment on AWS
                  </h1>
                  <p className="text-lg text-muted-foreground leading-relaxed">
                    Deploy ML models for real-time inference using Amazon SageMaker endpoints, API Gateway, 
                    and auto-scaling. Build production-ready prediction services.
                  </p>
                </div>

                {/* Meta Info */}
                <div className="flex flex-wrap items-center gap-6 text-sm text-muted-foreground mb-6">
                  <div className="flex items-center gap-1.5">
                    <Clock className="w-4 h-4" />
                    <span>5 hours</span>
                  </div>
                  <div className="flex items-center gap-1.5">
                    <Star className="w-4 h-4" />
                    <span>1,892 stars</span>
                  </div>
                  <div className="flex items-center gap-1.5">
                    <GitFork className="w-4 h-4" />
                    <span>523 forks</span>
                  </div>
                  <div className="flex items-center gap-1.5">
                    <Users className="w-4 h-4" />
                    <span>98 contributors</span>
                  </div>
                  <span className="px-2.5 py-1 rounded-full bg-amber-400/10 text-amber-400 border border-amber-400/20 text-xs font-medium">
                    Intermediate
                  </span>
                </div>

                {/* Action Buttons */}
                <div className="flex flex-wrap gap-3">
                  <Button variant="hero" size="lg">
                    <Github className="w-4 h-4 mr-2" />
                    View on GitHub
                  </Button>
                  <Button 
                    variant="outline" 
                    size="lg" 
                    className="border-foreground/20 hover:bg-foreground/5"
                    onClick={handleDownloadPDF}
                    disabled={isDownloading}
                  >
                    {isDownloading ? (
                      <Loader2 className="w-4 h-4 mr-2 animate-spin" />
                    ) : (
                      <Download className="w-4 h-4 mr-2" />
                    )}
                    {isDownloading ? 'Downloading...' : 'Download PDF'}
                  </Button>
                </div>
              </header>

              {/* Overview Section */}
              <section id="overview" className="mb-16">
                <h2 className="text-2xl font-bold text-foreground mb-4 flex items-center gap-3">
                  <button 
                    onClick={() => toggleProgress('overview')}
                    className="text-muted-foreground hover:text-teal-500 transition-colors"
                  >
                    {progress.includes('overview') ? (
                      <CheckCircle2 className="w-6 h-6 text-teal-500" />
                    ) : (
                      <Circle className="w-6 h-6" />
                    )}
                  </button>
                  Overview
                </h2>
                <p className="text-muted-foreground leading-relaxed mb-4">
                  Online deployment enables real-time predictions with low latency. AWS SageMaker provides 
                  fully managed endpoints that automatically handle infrastructure, scaling, and availability.
                </p>
                <p className="text-muted-foreground leading-relaxed mb-4">
                  In this guide, you'll learn to deploy models as REST APIs, configure auto-scaling based on 
                  traffic, and implement production best practices for security and monitoring.
                </p>

                <div className="grid grid-cols-1 md:grid-cols-3 gap-4 mt-8">
                  <div className="p-4 rounded-xl bg-card/50 border border-border">
                    <div className="text-2xl font-bold text-foreground mb-1">&lt;100ms</div>
                    <div className="text-sm text-muted-foreground">Typical Latency</div>
                  </div>
                  <div className="p-4 rounded-xl bg-card/50 border border-border">
                    <div className="text-2xl font-bold text-foreground mb-1">99.99%</div>
                    <div className="text-sm text-muted-foreground">SLA Uptime</div>
                  </div>
                  <div className="p-4 rounded-xl bg-card/50 border border-border">
                    <div className="text-2xl font-bold text-foreground mb-1">Auto</div>
                    <div className="text-sm text-muted-foreground">Scale to Zero</div>
                  </div>
                </div>
              </section>

              {/* Prerequisites Section */}
              <section id="prerequisites" className="mb-16">
                <h2 className="text-2xl font-bold text-foreground mb-4 flex items-center gap-3">
                  <button 
                    onClick={() => toggleProgress('prerequisites')}
                    className="text-muted-foreground hover:text-teal-500 transition-colors"
                  >
                    {progress.includes('prerequisites') ? (
                      <CheckCircle2 className="w-6 h-6 text-teal-500" />
                    ) : (
                      <Circle className="w-6 h-6" />
                    )}
                  </button>
                  Prerequisites
                </h2>
                <p className="text-muted-foreground leading-relaxed mb-4">
                  Before starting, ensure you have:
                </p>
                <ul className="space-y-3 text-muted-foreground">
                  <li className="flex items-start gap-3">
                    <ChevronRight className="w-5 h-5 text-teal-500 shrink-0 mt-0.5" />
                    <span><strong className="text-foreground">AWS Account</strong> — With SageMaker, API Gateway, and CloudWatch permissions</span>
                  </li>
                  <li className="flex items-start gap-3">
                    <ChevronRight className="w-5 h-5 text-teal-500 shrink-0 mt-0.5" />
                    <span><strong className="text-foreground">AWS CLI</strong> — Configured with appropriate credentials</span>
                  </li>
                  <li className="flex items-start gap-3">
                    <ChevronRight className="w-5 h-5 text-teal-500 shrink-0 mt-0.5" />
                    <span><strong className="text-foreground">Python 3.8+</strong> — With boto3 and sagemaker SDK</span>
                  </li>
                  <li className="flex items-start gap-3">
                    <ChevronRight className="w-5 h-5 text-teal-500 shrink-0 mt-0.5" />
                    <span><strong className="text-foreground">Trained Model</strong> — Artifacts stored in S3</span>
                  </li>
                </ul>

                <Callout type="warning" title="Cost Consideration">
                  Real-time endpoints run continuously and incur costs even when not receiving traffic. 
                  Consider using Serverless Inference for variable workloads.
                </Callout>
              </section>

              {/* Setup Section */}
              <section id="setup" className="mb-16">
                <h2 className="text-2xl font-bold text-foreground mb-4 flex items-center gap-3">
                  <button 
                    onClick={() => toggleProgress('setup')}
                    className="text-muted-foreground hover:text-teal-500 transition-colors"
                  >
                    {progress.includes('setup') ? (
                      <CheckCircle2 className="w-6 h-6 text-teal-500" />
                    ) : (
                      <Circle className="w-6 h-6" />
                    )}
                  </button>
                  AWS Setup
                </h2>
                <p className="text-muted-foreground leading-relaxed mb-4">
                  Install dependencies and configure your environment:
                </p>

                <CodeBlock 
                  language="bash"
                  filename="terminal"
                  code={`# Install required packages
pip install boto3 sagemaker requests

# Configure AWS CLI
aws configure`}
                  showLineNumbers={false}
                />

                <p className="text-muted-foreground leading-relaxed my-4">
                  Initialize the SageMaker session:
                </p>

                <CodeBlock 
                  filename="setup.py"
                  code={`import boto3
import sagemaker
from sagemaker import get_execution_role

# Initialize session
sagemaker_session = sagemaker.Session()
region = boto3.Session().region_name

# Get execution role
try:
    role = get_execution_role()
except ValueError:
    role = 'arn:aws:iam::YOUR_ACCOUNT_ID:role/SageMakerRole'

# S3 bucket for model artifacts
bucket = sagemaker_session.default_bucket()
prefix = 'online-deployment'

print(f"Region: {region}")
print(f"Role: {role}")
print(f"Bucket: {bucket}")`}
                />
              </section>

              {/* SageMaker Endpoints Section */}
              <section id="sagemaker-endpoints" className="mb-16">
                <h2 className="text-2xl font-bold text-foreground mb-4 flex items-center gap-3">
                  <button 
                    onClick={() => toggleProgress('sagemaker-endpoints')}
                    className="text-muted-foreground hover:text-teal-500 transition-colors"
                  >
                    {progress.includes('sagemaker-endpoints') ? (
                      <CheckCircle2 className="w-6 h-6 text-teal-500" />
                    ) : (
                      <Circle className="w-6 h-6" />
                    )}
                  </button>
                  SageMaker Endpoints
                </h2>
                <p className="text-muted-foreground leading-relaxed mb-8">
                  SageMaker endpoints provide managed infrastructure for hosting ML models with built-in 
                  load balancing and health checks.
                </p>

                {/* Real-Time Inference */}
                <div id="real-time-inference" className="mb-12">
                  <h3 className="text-xl font-semibold text-foreground mb-4">Real-Time Inference</h3>
                  <p className="text-muted-foreground leading-relaxed mb-4">
                    Deploy a model to a real-time endpoint:
                  </p>

                  <CodeBlock 
                    filename="deploy_endpoint.py"
                    code={`from sagemaker.model import Model

# Create a SageMaker model
model = Model(
    image_uri='YOUR_CONTAINER_IMAGE',
    model_data=f's3://{bucket}/{prefix}/model.tar.gz',
    role=role,
    sagemaker_session=sagemaker_session,
    name='my-realtime-model'
)

# Deploy to an endpoint
predictor = model.deploy(
    initial_instance_count=1,
    instance_type='ml.m5.large',
    endpoint_name='my-realtime-endpoint',
    wait=True
)

print(f"Endpoint deployed: {predictor.endpoint_name}")

# Make a prediction
import json

response = predictor.predict(
    data=json.dumps({'features': [1.0, 2.0, 3.0]}),
    initial_args={'ContentType': 'application/json'}
)

print(f"Prediction: {response}")`}
                  />

                  <Callout type="tip" title="Container Images">
                    AWS provides pre-built containers for popular frameworks like 
                    <InlineCode>sklearn</InlineCode>, <InlineCode>pytorch</InlineCode>, and 
                    <InlineCode>tensorflow</InlineCode>. Use them for faster deployment!
                  </Callout>
                </div>

                {/* Multi-Model Endpoints */}
                <div id="multi-model-endpoints" className="mb-12">
                  <h3 className="text-xl font-semibold text-foreground mb-4">Multi-Model Endpoints</h3>
                  <p className="text-muted-foreground leading-relaxed mb-4">
                    Host multiple models on a single endpoint to reduce costs:
                  </p>

                  <CodeBlock 
                    filename="multi_model_endpoint.py"
                    code={`from sagemaker.multidatamodel import MultiDataModel

# Create a multi-model endpoint
mme = MultiDataModel(
    name='multi-model-endpoint',
    model_data_prefix=f's3://{bucket}/{prefix}/models/',
    image_uri='YOUR_CONTAINER_IMAGE',
    role=role,
    sagemaker_session=sagemaker_session
)

# Deploy the multi-model endpoint
predictor = mme.deploy(
    initial_instance_count=1,
    instance_type='ml.m5.large',
    endpoint_name='multi-model-endpoint'
)

# Add models dynamically
mme.add_model(model_data_source=f's3://{bucket}/{prefix}/model_a.tar.gz')
mme.add_model(model_data_source=f's3://{bucket}/{prefix}/model_b.tar.gz')

# Invoke specific model
response = predictor.predict(
    data={'features': [1.0, 2.0, 3.0]},
    target_model='model_a.tar.gz'
)`}
                  />
                </div>
              </section>

              {/* API Gateway Section */}
              <section id="api-gateway" className="mb-16">
                <h2 className="text-2xl font-bold text-foreground mb-4 flex items-center gap-3">
                  <button 
                    onClick={() => toggleProgress('api-gateway')}
                    className="text-muted-foreground hover:text-teal-500 transition-colors"
                  >
                    {progress.includes('api-gateway') ? (
                      <CheckCircle2 className="w-6 h-6 text-teal-500" />
                    ) : (
                      <Circle className="w-6 h-6" />
                    )}
                  </button>
                  API Gateway Integration
                </h2>
                <p className="text-muted-foreground leading-relaxed mb-4">
                  Expose your SageMaker endpoint through API Gateway for additional features like 
                  authentication, rate limiting, and custom domains:
                </p>

                <CodeBlock 
                  filename="lambda_proxy.py"
                  code={`import json
import boto3

runtime = boto3.client('sagemaker-runtime')
ENDPOINT_NAME = 'my-realtime-endpoint'

def lambda_handler(event, context):
    """Lambda function to proxy requests to SageMaker."""
    
    try:
        # Parse request body
        body = json.loads(event.get('body', '{}'))
        
        # Invoke SageMaker endpoint
        response = runtime.invoke_endpoint(
            EndpointName=ENDPOINT_NAME,
            ContentType='application/json',
            Body=json.dumps(body)
        )
        
        # Parse response
        result = json.loads(response['Body'].read().decode())
        
        return {
            'statusCode': 200,
            'headers': {
                'Content-Type': 'application/json',
                'Access-Control-Allow-Origin': '*'
            },
            'body': json.dumps(result)
        }
        
    except Exception as e:
        return {
            'statusCode': 500,
            'body': json.dumps({'error': str(e)})
        }`}
                />

                <p className="text-muted-foreground leading-relaxed my-4">
                  Create the API Gateway REST API:
                </p>

                <CodeBlock 
                  language="bash"
                  filename="terminal"
                  code={`# Create REST API
aws apigateway create-rest-api \\
  --name "ML-Prediction-API" \\
  --description "API for ML predictions"

# Create resource and method
aws apigateway create-resource \\
  --rest-api-id YOUR_API_ID \\
  --parent-id YOUR_ROOT_ID \\
  --path-part "predict"

# Deploy the API
aws apigateway create-deployment \\
  --rest-api-id YOUR_API_ID \\
  --stage-name prod`}
                  showLineNumbers={false}
                />
              </section>

              {/* Auto Scaling Section */}
              <section id="auto-scaling" className="mb-16">
                <h2 className="text-2xl font-bold text-foreground mb-4 flex items-center gap-3">
                  <button 
                    onClick={() => toggleProgress('auto-scaling')}
                    className="text-muted-foreground hover:text-teal-500 transition-colors"
                  >
                    {progress.includes('auto-scaling') ? (
                      <CheckCircle2 className="w-6 h-6 text-teal-500" />
                    ) : (
                      <Circle className="w-6 h-6" />
                    )}
                  </button>
                  Auto Scaling
                </h2>
                <p className="text-muted-foreground leading-relaxed mb-4">
                  Configure auto-scaling to handle traffic variations:
                </p>

                <CodeBlock 
                  filename="auto_scaling.py"
                  code={`import boto3

autoscaling = boto3.client('application-autoscaling')

# Register scalable target
autoscaling.register_scalable_target(
    ServiceNamespace='sagemaker',
    ResourceId='endpoint/my-realtime-endpoint/variant/AllTraffic',
    ScalableDimension='sagemaker:variant:DesiredInstanceCount',
    MinCapacity=1,
    MaxCapacity=10
)

# Create scaling policy based on invocations
autoscaling.put_scaling_policy(
    PolicyName='InvocationScaling',
    ServiceNamespace='sagemaker',
    ResourceId='endpoint/my-realtime-endpoint/variant/AllTraffic',
    ScalableDimension='sagemaker:variant:DesiredInstanceCount',
    PolicyType='TargetTrackingScaling',
    TargetTrackingScalingPolicyConfiguration={
        'TargetValue': 1000.0,  # Target invocations per instance
        'PredefinedMetricSpecification': {
            'PredefinedMetricType': 'SageMakerVariantInvocationsPerInstance'
        },
        'ScaleInCooldown': 300,
        'ScaleOutCooldown': 60
    }
)

print("Auto-scaling configured successfully")`}
                />

                <div className="grid grid-cols-1 md:grid-cols-2 gap-4 mt-6">
                  <div className="p-4 rounded-xl bg-blue-500/10 border border-blue-500/20">
                    <div className="font-semibold text-blue-400 mb-1">Scale Out</div>
                    <div className="text-sm text-muted-foreground">60 second cooldown for rapid scaling during traffic spikes</div>
                  </div>
                  <div className="p-4 rounded-xl bg-purple-500/10 border border-purple-500/20">
                    <div className="font-semibold text-purple-400 mb-1">Scale In</div>
                    <div className="text-sm text-muted-foreground">300 second cooldown to prevent premature scaling down</div>
                  </div>
                </div>
              </section>

              {/* Load Testing Section */}
              <section id="load-testing" className="mb-16">
                <h2 className="text-2xl font-bold text-foreground mb-4 flex items-center gap-3">
                  <button 
                    onClick={() => toggleProgress('load-testing')}
                    className="text-muted-foreground hover:text-teal-500 transition-colors"
                  >
                    {progress.includes('load-testing') ? (
                      <CheckCircle2 className="w-6 h-6 text-teal-500" />
                    ) : (
                      <Circle className="w-6 h-6" />
                    )}
                  </button>
                  Load Testing
                </h2>
                <p className="text-muted-foreground leading-relaxed mb-4">
                  Test your endpoint performance before going to production:
                </p>

                <CodeBlock 
                  filename="load_test.py"
                  code={`import boto3
import time
import concurrent.futures
import statistics

runtime = boto3.client('sagemaker-runtime')
ENDPOINT_NAME = 'my-realtime-endpoint'

def invoke_endpoint(payload):
    """Single invocation with timing."""
    start = time.time()
    
    response = runtime.invoke_endpoint(
        EndpointName=ENDPOINT_NAME,
        ContentType='application/json',
        Body=payload
    )
    
    latency = (time.time() - start) * 1000  # ms
    return latency

def run_load_test(num_requests=100, concurrency=10):
    """Run load test with concurrent requests."""
    
    payload = '{"features": [1.0, 2.0, 3.0]}'
    latencies = []
    errors = 0
    
    start_time = time.time()
    
    with concurrent.futures.ThreadPoolExecutor(max_workers=concurrency) as executor:
        futures = [executor.submit(invoke_endpoint, payload) 
                   for _ in range(num_requests)]
        
        for future in concurrent.futures.as_completed(futures):
            try:
                latencies.append(future.result())
            except Exception as e:
                errors += 1
    
    total_time = time.time() - start_time
    
    # Calculate statistics
    print(f"\\n=== Load Test Results ===")
    print(f"Total requests: {num_requests}")
    print(f"Concurrency: {concurrency}")
    print(f"Total time: {total_time:.2f}s")
    print(f"Throughput: {num_requests/total_time:.2f} req/s")
    print(f"\\nLatency (ms):")
    print(f"  Mean: {statistics.mean(latencies):.2f}")
    print(f"  Median: {statistics.median(latencies):.2f}")
    print(f"  P95: {sorted(latencies)[int(0.95*len(latencies))]:.2f}")
    print(f"  P99: {sorted(latencies)[int(0.99*len(latencies))]:.2f}")
    print(f"\\nErrors: {errors}")

# Run the test
run_load_test(num_requests=1000, concurrency=20)`}
                />

                <OutputBlock 
                  output={`=== Load Test Results ===
Total requests: 1000
Concurrency: 20
Total time: 15.34s
Throughput: 65.18 req/s

Latency (ms):
  Mean: 287.45
  Median: 256.12
  P95: 498.23
  P99: 612.87

Errors: 0`}
                  title="Load Test Output"
                />
              </section>

              {/* Monitoring Section */}
              <section id="monitoring" className="mb-16">
                <h2 className="text-2xl font-bold text-foreground mb-4 flex items-center gap-3">
                  <button 
                    onClick={() => toggleProgress('monitoring')}
                    className="text-muted-foreground hover:text-teal-500 transition-colors"
                  >
                    {progress.includes('monitoring') ? (
                      <CheckCircle2 className="w-6 h-6 text-teal-500" />
                    ) : (
                      <Circle className="w-6 h-6" />
                    )}
                  </button>
                  Monitoring & Alerts
                </h2>
                <p className="text-muted-foreground leading-relaxed mb-4">
                  Set up CloudWatch dashboards and alerts for your endpoints:
                </p>

                <CodeBlock 
                  filename="monitoring.py"
                  code={`import boto3

cloudwatch = boto3.client('cloudwatch')
ENDPOINT_NAME = 'my-realtime-endpoint'

# Create CloudWatch alarm for high latency
cloudwatch.put_metric_alarm(
    AlarmName='HighEndpointLatency',
    MetricName='ModelLatency',
    Namespace='AWS/SageMaker',
    Dimensions=[
        {'Name': 'EndpointName', 'Value': ENDPOINT_NAME},
        {'Name': 'VariantName', 'Value': 'AllTraffic'}
    ],
    Statistic='Average',
    Period=60,
    EvaluationPeriods=3,
    Threshold=500000,  # 500ms in microseconds
    ComparisonOperator='GreaterThanThreshold',
    AlarmActions=['arn:aws:sns:REGION:ACCOUNT:alerts']
)

# Create alarm for 5xx errors
cloudwatch.put_metric_alarm(
    AlarmName='Endpoint5xxErrors',
    MetricName='Invocation5XXErrors',
    Namespace='AWS/SageMaker',
    Dimensions=[
        {'Name': 'EndpointName', 'Value': ENDPOINT_NAME},
        {'Name': 'VariantName', 'Value': 'AllTraffic'}
    ],
    Statistic='Sum',
    Period=60,
    EvaluationPeriods=1,
    Threshold=10,
    ComparisonOperator='GreaterThanThreshold',
    AlarmActions=['arn:aws:sns:REGION:ACCOUNT:alerts']
)

print("Alarms created successfully")`}
                />
              </section>

              {/* Security Section */}
              <section id="security" className="mb-16">
                <h2 className="text-2xl font-bold text-foreground mb-4 flex items-center gap-3">
                  <button 
                    onClick={() => toggleProgress('security')}
                    className="text-muted-foreground hover:text-teal-500 transition-colors"
                  >
                    {progress.includes('security') ? (
                      <CheckCircle2 className="w-6 h-6 text-teal-500" />
                    ) : (
                      <Circle className="w-6 h-6" />
                    )}
                  </button>
                  Security Best Practices
                </h2>
                <p className="text-muted-foreground leading-relaxed mb-4">
                  Secure your ML endpoints in production:
                </p>

                <div className="space-y-4 mb-6">
                  <div className="p-4 rounded-xl bg-card/50 border border-border">
                    <h4 className="font-semibold text-foreground mb-2">VPC Deployment</h4>
                    <p className="text-sm text-muted-foreground mb-3">
                      Deploy endpoints in a VPC to restrict network access:
                    </p>
                    <CodeBlock 
                      filename="vpc_config.py"
                      code={`model = Model(
    image_uri='YOUR_IMAGE',
    model_data='s3://bucket/model.tar.gz',
    role=role,
    vpc_config={
        'SecurityGroupIds': ['sg-xxxxxx'],
        'Subnets': ['subnet-xxxxxx', 'subnet-yyyyyy']
    }
)`}
                    />
                  </div>

                  <div className="p-4 rounded-xl bg-card/50 border border-border">
                    <h4 className="font-semibold text-foreground mb-2">Encryption</h4>
                    <p className="text-sm text-muted-foreground">
                      Enable encryption at rest and in transit. Use AWS KMS for key management.
                      SageMaker encrypts all inter-container traffic by default.
                    </p>
                  </div>

                  <div className="p-4 rounded-xl bg-card/50 border border-border">
                    <h4 className="font-semibold text-foreground mb-2">IAM Policies</h4>
                    <p className="text-sm text-muted-foreground">
                      Use least-privilege IAM policies. Only grant 
                      <InlineCode>sagemaker:InvokeEndpoint</InlineCode> to services that need prediction access.
                    </p>
                  </div>
                </div>
              </section>

              {/* Complete Example Section */}
              <section id="example" className="mb-16">
                <h2 className="text-2xl font-bold text-foreground mb-4 flex items-center gap-3">
                  <button 
                    onClick={() => toggleProgress('example')}
                    className="text-muted-foreground hover:text-teal-500 transition-colors"
                  >
                    {progress.includes('example') ? (
                      <CheckCircle2 className="w-6 h-6 text-teal-500" />
                    ) : (
                      <Circle className="w-6 h-6" />
                    )}
                  </button>
                  Complete Example
                </h2>
                <p className="text-muted-foreground leading-relaxed mb-4">
                  A complete end-to-end example for deploying a real-time inference endpoint:
                </p>

                <CodeBlock 
                  filename="complete_online_deployment.py"
                  code={`import boto3
import sagemaker
from sagemaker.sklearn import SKLearnModel
import json

# Initialize
sagemaker_session = sagemaker.Session()
role = 'arn:aws:iam::YOUR_ACCOUNT:role/SageMakerRole'
bucket = sagemaker_session.default_bucket()

# 1. Create model from artifacts
print("Creating model...")
model = SKLearnModel(
    model_data=f's3://{bucket}/models/sklearn-model.tar.gz',
    role=role,
    framework_version='1.0-1',
    py_version='py3',
    sagemaker_session=sagemaker_session
)

# 2. Deploy endpoint
print("Deploying endpoint...")
predictor = model.deploy(
    initial_instance_count=1,
    instance_type='ml.m5.large',
    endpoint_name='sklearn-realtime-endpoint'
)

# 3. Configure auto-scaling
print("Configuring auto-scaling...")
autoscaling = boto3.client('application-autoscaling')

autoscaling.register_scalable_target(
    ServiceNamespace='sagemaker',
    ResourceId='endpoint/sklearn-realtime-endpoint/variant/AllTraffic',
    ScalableDimension='sagemaker:variant:DesiredInstanceCount',
    MinCapacity=1,
    MaxCapacity=5
)

autoscaling.put_scaling_policy(
    PolicyName='TargetTracking',
    ServiceNamespace='sagemaker',
    ResourceId='endpoint/sklearn-realtime-endpoint/variant/AllTraffic',
    ScalableDimension='sagemaker:variant:DesiredInstanceCount',
    PolicyType='TargetTrackingScaling',
    TargetTrackingScalingPolicyConfiguration={
        'TargetValue': 500.0,
        'PredefinedMetricSpecification': {
            'PredefinedMetricType': 'SageMakerVariantInvocationsPerInstance'
        }
    }
)

# 4. Test the endpoint
print("\\nTesting endpoint...")
test_data = {'features': [[1.0, 2.0, 3.0, 4.0]]}
response = predictor.predict(test_data)
print(f"Prediction: {response}")

# 5. Set up monitoring
print("\\nSetting up monitoring...")
cloudwatch = boto3.client('cloudwatch')
cloudwatch.put_metric_alarm(
    AlarmName='EndpointLatencyAlarm',
    MetricName='ModelLatency',
    Namespace='AWS/SageMaker',
    Dimensions=[
        {'Name': 'EndpointName', 'Value': 'sklearn-realtime-endpoint'},
        {'Name': 'VariantName', 'Value': 'AllTraffic'}
    ],
    Statistic='Average',
    Period=60,
    EvaluationPeriods=3,
    Threshold=500000,
    ComparisonOperator='GreaterThanThreshold'
)

print("\\n✅ Deployment complete!")
print(f"Endpoint: sklearn-realtime-endpoint")
print(f"Auto-scaling: 1-5 instances")
print(f"Monitoring: CloudWatch alarms configured")`}
                />
              </section>

              {/* Next Steps */}
              <section id="next-steps" className="mb-16">
                <h2 className="text-2xl font-bold text-foreground mb-4 flex items-center gap-3">
                  <button 
                    onClick={() => toggleProgress('next-steps')}
                    className="text-muted-foreground hover:text-teal-500 transition-colors"
                  >
                    {progress.includes('next-steps') ? (
                      <CheckCircle2 className="w-6 h-6 text-teal-500" />
                    ) : (
                      <Circle className="w-6 h-6" />
                    )}
                  </button>
                  Next Steps
                </h2>
                <p className="text-muted-foreground leading-relaxed mb-6">
                  You've learned to deploy real-time ML endpoints on AWS. Continue your journey:
                </p>

                <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                  <Link to="/docs/batchdeployment/aws" className="group p-6 rounded-2xl bg-card/50 border border-border hover:border-foreground/20 hover:shadow-lg hover:shadow-foreground/5 transition-all">
                    <h3 className="font-semibold text-foreground mb-1 group-hover:text-teal-500 transition-colors">
                      Batch Deployment on AWS
                    </h3>
                    <p className="text-sm text-muted-foreground">
                      Process large datasets with batch inference
                    </p>
                  </Link>

                  <Link to="/docs/onlinedeployment/gcp" className="group p-6 rounded-2xl bg-card/50 border border-border hover:border-foreground/20 hover:shadow-lg hover:shadow-foreground/5 transition-all">
                    <h3 className="font-semibold text-foreground mb-1 group-hover:text-teal-500 transition-colors">
                      Online Deployment on GCP
                    </h3>
                    <p className="text-sm text-muted-foreground">
                      Compare with Google Cloud's approach
                    </p>
                  </Link>

                  <Link to="/projects/neural-network" className="group p-6 rounded-2xl bg-card/50 border border-border hover:border-foreground/20 hover:shadow-lg hover:shadow-foreground/5 transition-all">
                    <h3 className="font-semibold text-foreground mb-1 group-hover:text-teal-500 transition-colors">
                      Build a Neural Network
                    </h3>
                    <p className="text-sm text-muted-foreground">
                      Create a model from scratch to deploy
                    </p>
                  </Link>

                  <Link to="/docs" className="group p-6 rounded-2xl bg-card/50 border border-border hover:border-foreground/20 hover:shadow-lg hover:shadow-foreground/5 transition-all">
                    <h3 className="font-semibold text-foreground mb-1 group-hover:text-teal-500 transition-colors">
                      Explore More Docs
                    </h3>
                    <p className="text-sm text-muted-foreground">
                      Browse all documentation
                    </p>
                  </Link>
                </div>
              </section>

              {/* Footer Navigation */}
              <div className="flex items-center justify-between pt-8 border-t border-border">
                <Link to="/docs/model-deployment" className="flex items-center gap-2 text-muted-foreground hover:text-foreground transition-colors">
                  <ArrowLeft className="w-4 h-4" />
                  Back to Model Deployment
                </Link>
                <a 
                  href="https://github.com" 
                  target="_blank" 
                  rel="noopener noreferrer"
                  className="flex items-center gap-2 text-muted-foreground hover:text-foreground transition-colors"
                >
                  Edit on GitHub
                  <ExternalLink className="w-4 h-4" />
                </a>
              </div>
            </article>

            {/* Right Sidebar */}
            <aside className="hidden xl:block w-56 shrink-0">
              <div className="sticky top-28">
                <div className="flex items-center gap-2 mb-4">
                  <List className="w-4 h-4 text-muted-foreground" />
                  <span className="text-sm font-medium text-foreground">On this page</span>
                </div>
                <nav className="space-y-1 mb-6">
                  {sections.map((section) => (
                    <button
                      key={section.id}
                      onClick={() => scrollToSection(section.id)}
                      className={`block w-full text-left text-sm py-1.5 transition-colors ${
                        section.parent ? 'pl-4' : ''
                      } ${
                        activeSection === section.id
                          ? 'text-teal-500 font-medium'
                          : 'text-muted-foreground hover:text-foreground'
                      }`}
                    >
                      {section.title}
                    </button>
                  ))}
                </nav>
              </div>
            </aside>
          </div>
        </div>
      </main>
      
      <Footer />
    </div>
  );
};

export default OnlineDeploymentAWS;
