import { useState, useEffect, useRef } from 'react';
import { Link } from 'react-router-dom';
import Navbar from '@/components/layout/Navbar';
import Footer from '@/components/layout/Footer';
import { CodeBlock, Callout, OutputBlock, InlineCode } from '@/components/project/CodeBlock';
import { 
  ChevronRight, 
  Clock, 
  Users, 
  Star, 
  GitFork,
  ArrowLeft,
  Github,
  BookOpen,
  List,
  ExternalLink,
  CheckCircle2,
  Circle,
  Download,
  Loader2,
  Globe
} from 'lucide-react';
import { Button } from '@/components/ui/button';

const sections = [
  { id: 'overview', title: 'Overview' },
  { id: 'prerequisites', title: 'Prerequisites' },
  { id: 'setup', title: 'GCP Setup' },
  { id: 'vertex-endpoints', title: 'Vertex AI Endpoints' },
  { id: 'online-prediction', title: 'Online Prediction', parent: 'vertex-endpoints' },
  { id: 'custom-prediction', title: 'Custom Prediction Routines', parent: 'vertex-endpoints' },
  { id: 'cloud-run', title: 'Cloud Run Deployment' },
  { id: 'auto-scaling', title: 'Auto Scaling' },
  { id: 'load-balancing', title: 'Load Balancing' },
  { id: 'monitoring', title: 'Monitoring & Logging' },
  { id: 'security', title: 'Security Best Practices' },
  { id: 'example', title: 'Complete Example' },
  { id: 'next-steps', title: 'Next Steps' },
];

const OnlineDeploymentGCP = () => {
  const [activeSection, setActiveSection] = useState('overview');
  const [sidebarOpen, setSidebarOpen] = useState(false);
  const [progress, setProgress] = useState<string[]>([]);
  const [isDownloading, setIsDownloading] = useState(false);
  const contentRef = useRef<HTMLElement>(null);

  const handleDownloadPDF = async () => {
    setIsDownloading(true);
    
    const pdfContent = `
ONLINE DEPLOYMENT ON GCP
============================

A Complete Guide to Deploying ML Models for Real-Time Inference on Google Cloud Platform

Difficulty: Intermediate
Estimated Time: 5 hours

TABLE OF CONTENTS
-----------------
1. Overview
2. Prerequisites
3. GCP Setup
4. Vertex AI Endpoints
   - Online Prediction
   - Custom Prediction Routines
5. Cloud Run Deployment
6. Auto Scaling
7. Load Balancing
8. Monitoring & Logging
9. Security Best Practices
10. Complete Example
11. Next Steps

---
Generated by MLCodex.dev
Online Deployment on GCP
`;

    const blob = new Blob([pdfContent], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    
    const link = document.createElement('a');
    link.href = url;
    link.download = 'online-deployment-gcp.txt';
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
    
    setTimeout(() => {
      setIsDownloading(false);
    }, 1000);
  };

  useEffect(() => {
    const handleScroll = () => {
      const sectionElements = sections.map(s => ({
        id: s.id,
        element: document.getElementById(s.id)
      })).filter(s => s.element);

      for (const section of sectionElements.reverse()) {
        if (section.element) {
          const rect = section.element.getBoundingClientRect();
          if (rect.top <= 120) {
            setActiveSection(section.id);
            break;
          }
        }
      }
    };

    window.addEventListener('scroll', handleScroll);
    return () => window.removeEventListener('scroll', handleScroll);
  }, []);

  const scrollToSection = (id: string) => {
    const element = document.getElementById(id);
    if (element) {
      const offset = 100;
      const elementPosition = element.getBoundingClientRect().top + window.scrollY;
      window.scrollTo({ top: elementPosition - offset, behavior: 'smooth' });
    }
  };

  const toggleProgress = (sectionId: string) => {
    setProgress(prev => 
      prev.includes(sectionId) 
        ? prev.filter(id => id !== sectionId)
        : [...prev, sectionId]
    );
  };

  return (
    <div className="min-h-screen bg-background relative">
      <div className="noise-overlay" />
      <Navbar variant="simple" />
      
      <main className="pt-24 pb-20" ref={contentRef}>
        <div className="container mx-auto px-6">
          {/* Breadcrumb */}
          <div className="flex items-center gap-2 text-sm text-muted-foreground mb-8">
            <Link to="/docs" className="hover:text-foreground transition-colors">Docs</Link>
            <ChevronRight className="w-4 h-4" />
            <Link to="/docs/model-deployment" className="hover:text-foreground transition-colors">Model Deployment</Link>
            <ChevronRight className="w-4 h-4" />
            <span className="text-foreground">Online Deployment - GCP</span>
          </div>

          <div className="flex gap-8 lg:gap-12">
            {/* Left Sidebar */}
            <aside className="hidden lg:block w-64 shrink-0">
              <div className="sticky top-28">
                <div className="flex items-center gap-2 mb-4">
                  <BookOpen className="w-4 h-4 text-muted-foreground" />
                  <span className="text-sm font-medium text-foreground">Related Docs</span>
                </div>
                <nav className="space-y-1">
                  {[
                    { slug: '/docs/onlinedeployment/aws', title: 'Online Deploy on AWS' },
                    { slug: '/docs/batchdeployment/aws', title: 'Batch Deploy on AWS' },
                    { slug: '/docs/batchdeployment/gcp', title: 'Batch Deploy on GCP' },
                  ].map((doc) => (
                    <Link
                      key={doc.slug}
                      to={doc.slug}
                      className="block py-1.5 text-sm text-muted-foreground hover:text-foreground transition-colors"
                    >
                      {doc.title}
                    </Link>
                  ))}
                </nav>

                <Link 
                  to="/docs/model-deployment"
                  className="flex items-center gap-2 mt-4 text-sm text-muted-foreground hover:text-foreground transition-colors"
                >
                  View all deployment docs
                  <ChevronRight className="w-4 h-4" />
                </Link>

                {/* Progress Tracker */}
                <div className="mt-8 pt-6 border-t border-border">
                  <div className="text-sm font-medium text-foreground mb-3">Your Progress</div>
                  <div className="text-xs text-muted-foreground mb-2">
                    {progress.length} / {sections.filter(s => !s.parent).length} sections completed
                  </div>
                  <div className="w-full h-2 rounded-full bg-foreground/10">
                    <div 
                      className="h-full rounded-full bg-gradient-to-r from-teal-500 to-cyan-500 transition-all"
                      style={{ width: `${(progress.length / sections.filter(s => !s.parent).length) * 100}%` }}
                    />
                  </div>
                </div>

                {/* Quick Actions */}
                <div className="mt-6 pt-6 border-t border-border">
                  <div className="text-sm font-medium text-foreground mb-3">Quick Actions</div>
                  <div className="space-y-2">
                    <a 
                      href="https://github.com" 
                      target="_blank" 
                      rel="noopener noreferrer"
                      className="flex items-center gap-2 text-sm text-muted-foreground hover:text-foreground transition-colors py-1"
                    >
                      <Github className="w-4 h-4" />
                      View Source
                    </a>
                    <button 
                      onClick={handleDownloadPDF}
                      disabled={isDownloading}
                      className="flex items-center gap-2 text-sm text-muted-foreground hover:text-foreground transition-colors py-1 disabled:opacity-50"
                    >
                      {isDownloading ? (
                        <Loader2 className="w-4 h-4 animate-spin" />
                      ) : (
                        <Download className="w-4 h-4" />
                      )}
                      {isDownloading ? 'Downloading...' : 'Download PDF'}
                    </button>
                  </div>
                </div>
              </div>
            </aside>

            {/* Main Content */}
            <article className="flex-1 min-w-0 max-w-4xl">
              {/* Header */}
              <header className="mb-12">
                <div className="mb-6">
                  <div className="flex items-center gap-3 mb-4">
                    <div className="w-12 h-12 rounded-xl bg-blue-500/10 border border-blue-500/20 flex items-center justify-center">
                      <Globe className="w-6 h-6 text-blue-400" />
                    </div>
                    <span className="text-[10px] px-2.5 py-1 rounded-full bg-blue-500/10 text-blue-400 border border-blue-500/20 font-medium uppercase tracking-wider">
                      GCP
                    </span>
                  </div>
                  <h1 className="text-4xl lg:text-5xl font-bold tracking-tight mb-4">
                    Online Deployment on GCP
                  </h1>
                  <p className="text-lg text-muted-foreground leading-relaxed">
                    Deploy ML models for real-time inference using Vertex AI endpoints, Cloud Run, 
                    and load balancing. Build low-latency prediction services at scale.
                  </p>
                </div>

                {/* Meta Info */}
                <div className="flex flex-wrap items-center gap-6 text-sm text-muted-foreground mb-6">
                  <div className="flex items-center gap-1.5">
                    <Clock className="w-4 h-4" />
                    <span>5 hours</span>
                  </div>
                  <div className="flex items-center gap-1.5">
                    <Star className="w-4 h-4" />
                    <span>1,456 stars</span>
                  </div>
                  <div className="flex items-center gap-1.5">
                    <GitFork className="w-4 h-4" />
                    <span>398 forks</span>
                  </div>
                  <div className="flex items-center gap-1.5">
                    <Users className="w-4 h-4" />
                    <span>82 contributors</span>
                  </div>
                  <span className="px-2.5 py-1 rounded-full bg-amber-400/10 text-amber-400 border border-amber-400/20 text-xs font-medium">
                    Intermediate
                  </span>
                </div>

                {/* Action Buttons */}
                <div className="flex flex-wrap gap-3">
                  <Button variant="hero" size="lg">
                    <Github className="w-4 h-4 mr-2" />
                    View on GitHub
                  </Button>
                  <Button 
                    variant="outline" 
                    size="lg" 
                    className="border-foreground/20 hover:bg-foreground/5"
                    onClick={handleDownloadPDF}
                    disabled={isDownloading}
                  >
                    {isDownloading ? (
                      <Loader2 className="w-4 h-4 mr-2 animate-spin" />
                    ) : (
                      <Download className="w-4 h-4 mr-2" />
                    )}
                    {isDownloading ? 'Downloading...' : 'Download PDF'}
                  </Button>
                </div>
              </header>

              {/* Overview Section */}
              <section id="overview" className="mb-16">
                <h2 className="text-2xl font-bold text-foreground mb-4 flex items-center gap-3">
                  <button 
                    onClick={() => toggleProgress('overview')}
                    className="text-muted-foreground hover:text-teal-500 transition-colors"
                  >
                    {progress.includes('overview') ? (
                      <CheckCircle2 className="w-6 h-6 text-teal-500" />
                    ) : (
                      <Circle className="w-6 h-6" />
                    )}
                  </button>
                  Overview
                </h2>
                <p className="text-muted-foreground leading-relaxed mb-4">
                  Google Cloud offers multiple options for deploying ML models for real-time inference. 
                  Vertex AI provides managed endpoints with auto-scaling, while Cloud Run offers 
                  containerized deployments with pay-per-request pricing.
                </p>
                <p className="text-muted-foreground leading-relaxed mb-4">
                  This guide covers deploying models using Vertex AI endpoints, custom prediction 
                  routines, Cloud Run, and implementing production features like auto-scaling and monitoring.
                </p>

                <div className="grid grid-cols-1 md:grid-cols-3 gap-4 mt-8">
                  <div className="p-4 rounded-xl bg-card/50 border border-border">
                    <div className="text-2xl font-bold text-foreground mb-1">&lt;50ms</div>
                    <div className="text-sm text-muted-foreground">P95 Latency</div>
                  </div>
                  <div className="p-4 rounded-xl bg-card/50 border border-border">
                    <div className="text-2xl font-bold text-foreground mb-1">99.95%</div>
                    <div className="text-sm text-muted-foreground">SLA Availability</div>
                  </div>
                  <div className="p-4 rounded-xl bg-card/50 border border-border">
                    <div className="text-2xl font-bold text-foreground mb-1">Global</div>
                    <div className="text-sm text-muted-foreground">Edge Locations</div>
                  </div>
                </div>
              </section>

              {/* Prerequisites Section */}
              <section id="prerequisites" className="mb-16">
                <h2 className="text-2xl font-bold text-foreground mb-4 flex items-center gap-3">
                  <button 
                    onClick={() => toggleProgress('prerequisites')}
                    className="text-muted-foreground hover:text-teal-500 transition-colors"
                  >
                    {progress.includes('prerequisites') ? (
                      <CheckCircle2 className="w-6 h-6 text-teal-500" />
                    ) : (
                      <Circle className="w-6 h-6" />
                    )}
                  </button>
                  Prerequisites
                </h2>
                <p className="text-muted-foreground leading-relaxed mb-4">
                  Before starting, ensure you have:
                </p>
                <ul className="space-y-3 text-muted-foreground">
                  <li className="flex items-start gap-3">
                    <ChevronRight className="w-5 h-5 text-teal-500 shrink-0 mt-0.5" />
                    <span><strong className="text-foreground">GCP Account</strong> — With billing enabled and Vertex AI API access</span>
                  </li>
                  <li className="flex items-start gap-3">
                    <ChevronRight className="w-5 h-5 text-teal-500 shrink-0 mt-0.5" />
                    <span><strong className="text-foreground">gcloud CLI</strong> — Installed and authenticated</span>
                  </li>
                  <li className="flex items-start gap-3">
                    <ChevronRight className="w-5 h-5 text-teal-500 shrink-0 mt-0.5" />
                    <span><strong className="text-foreground">Python 3.8+</strong> — With google-cloud-aiplatform SDK</span>
                  </li>
                  <li className="flex items-start gap-3">
                    <ChevronRight className="w-5 h-5 text-teal-500 shrink-0 mt-0.5" />
                    <span><strong className="text-foreground">Docker</strong> — For custom container deployments</span>
                  </li>
                </ul>

                <Callout type="tip" title="Free Tier">
                  Vertex AI includes a free tier with $300 in credits for new users. Cloud Run also 
                  offers a generous free tier with 2 million requests per month.
                </Callout>
              </section>

              {/* Setup Section */}
              <section id="setup" className="mb-16">
                <h2 className="text-2xl font-bold text-foreground mb-4 flex items-center gap-3">
                  <button 
                    onClick={() => toggleProgress('setup')}
                    className="text-muted-foreground hover:text-teal-500 transition-colors"
                  >
                    {progress.includes('setup') ? (
                      <CheckCircle2 className="w-6 h-6 text-teal-500" />
                    ) : (
                      <Circle className="w-6 h-6" />
                    )}
                  </button>
                  GCP Setup
                </h2>
                <p className="text-muted-foreground leading-relaxed mb-4">
                  Install dependencies and configure your environment:
                </p>

                <CodeBlock 
                  language="bash"
                  filename="terminal"
                  code={`# Install required packages
pip install google-cloud-aiplatform google-cloud-run requests

# Authenticate
gcloud auth application-default login

# Set project
gcloud config set project YOUR_PROJECT_ID

# Enable APIs
gcloud services enable aiplatform.googleapis.com
gcloud services enable run.googleapis.com
gcloud services enable cloudbuild.googleapis.com`}
                  showLineNumbers={false}
                />

                <p className="text-muted-foreground leading-relaxed my-4">
                  Initialize Vertex AI:
                </p>

                <CodeBlock 
                  filename="setup.py"
                  code={`from google.cloud import aiplatform

# Configuration
PROJECT_ID = "your-project-id"
REGION = "us-central1"
BUCKET_NAME = f"{PROJECT_ID}-online-deployment"

# Initialize Vertex AI
aiplatform.init(
    project=PROJECT_ID,
    location=REGION,
    staging_bucket=f"gs://{BUCKET_NAME}"
)

print(f"Project: {PROJECT_ID}")
print(f"Region: {REGION}")
print(f"Staging bucket: gs://{BUCKET_NAME}")`}
                />
              </section>

              {/* Vertex AI Endpoints Section */}
              <section id="vertex-endpoints" className="mb-16">
                <h2 className="text-2xl font-bold text-foreground mb-4 flex items-center gap-3">
                  <button 
                    onClick={() => toggleProgress('vertex-endpoints')}
                    className="text-muted-foreground hover:text-teal-500 transition-colors"
                  >
                    {progress.includes('vertex-endpoints') ? (
                      <CheckCircle2 className="w-6 h-6 text-teal-500" />
                    ) : (
                      <Circle className="w-6 h-6" />
                    )}
                  </button>
                  Vertex AI Endpoints
                </h2>
                <p className="text-muted-foreground leading-relaxed mb-8">
                  Vertex AI endpoints provide fully managed infrastructure for hosting ML models 
                  with automatic scaling and traffic management.
                </p>

                {/* Online Prediction */}
                <div id="online-prediction" className="mb-12">
                  <h3 className="text-xl font-semibold text-foreground mb-4">Online Prediction</h3>
                  <p className="text-muted-foreground leading-relaxed mb-4">
                    Deploy a model to a Vertex AI endpoint:
                  </p>

                  <CodeBlock 
                    filename="deploy_endpoint.py"
                    code={`from google.cloud import aiplatform

# Upload model to Model Registry
model = aiplatform.Model.upload(
    display_name="my-online-model",
    artifact_uri="gs://your-bucket/model-artifacts/",
    serving_container_image_uri="us-docker.pkg.dev/vertex-ai/prediction/sklearn-cpu.1-0:latest",
)

print(f"Model uploaded: {model.resource_name}")

# Create an endpoint
endpoint = aiplatform.Endpoint.create(
    display_name="my-prediction-endpoint",
    description="Production prediction endpoint"
)

print(f"Endpoint created: {endpoint.resource_name}")

# Deploy model to endpoint
deployed_model = model.deploy(
    endpoint=endpoint,
    deployed_model_display_name="v1",
    machine_type="n1-standard-4",
    min_replica_count=1,
    max_replica_count=5,
    traffic_percentage=100,
    sync=True
)

print(f"Model deployed to endpoint: {endpoint.display_name}")`}
                  />

                  <p className="text-muted-foreground leading-relaxed my-4">
                    Make predictions:
                  </p>

                  <CodeBlock 
                    filename="predict.py"
                    code={`# Get the endpoint
endpoint = aiplatform.Endpoint(endpoint_name="YOUR_ENDPOINT_ID")

# Make predictions
instances = [
    {"feature1": 1.0, "feature2": 2.0, "feature3": 3.0},
    {"feature1": 4.0, "feature2": 5.0, "feature3": 6.0}
]

predictions = endpoint.predict(instances=instances)

print("Predictions:")
for i, pred in enumerate(predictions.predictions):
    print(f"  Instance {i}: {pred}")`}
                  />

                  <OutputBlock 
                    output={`Predictions:
  Instance 0: [0.234]
  Instance 1: [0.876]`}
                    title="Output"
                  />
                </div>

                {/* Custom Prediction Routines */}
                <div id="custom-prediction" className="mb-12">
                  <h3 className="text-xl font-semibold text-foreground mb-4">Custom Prediction Routines</h3>
                  <p className="text-muted-foreground leading-relaxed mb-4">
                    For custom preprocessing or postprocessing, create a custom prediction routine:
                  </p>

                  <CodeBlock 
                    filename="predictor.py"
                    code={`from google.cloud.aiplatform.prediction import Predictor
import numpy as np
import joblib

class CustomPredictor(Predictor):
    """Custom predictor with preprocessing."""
    
    def __init__(self):
        self._model = None
        self._scaler = None
    
    def load(self, artifacts_uri: str) -> None:
        """Load model and preprocessing artifacts."""
        self._model = joblib.load(f"{artifacts_uri}/model.joblib")
        self._scaler = joblib.load(f"{artifacts_uri}/scaler.joblib")
    
    def preprocess(self, prediction_input: dict) -> np.ndarray:
        """Preprocess input data."""
        instances = prediction_input.get("instances", [])
        features = np.array([list(inst.values()) for inst in instances])
        return self._scaler.transform(features)
    
    def predict(self, instances: np.ndarray) -> np.ndarray:
        """Run model prediction."""
        return self._model.predict(instances)
    
    def postprocess(self, prediction_results: np.ndarray) -> dict:
        """Format prediction output."""
        return {
            "predictions": prediction_results.tolist(),
            "model_version": "1.0"
        }`}
                  />

                  <CodeBlock 
                    filename="Dockerfile"
                    code={`FROM us-docker.pkg.dev/vertex-ai/prediction/sklearn-cpu.1-0:latest

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY predictor.py .
COPY model/ ./model/

ENV AIP_HEALTH_ROUTE=/health
ENV AIP_PREDICT_ROUTE=/predict
ENV AIP_HTTP_PORT=8080

EXPOSE 8080

CMD ["python", "-m", "google.cloud.aiplatform.prediction.model_server"]`}
                  />
                </div>
              </section>

              {/* Cloud Run Section */}
              <section id="cloud-run" className="mb-16">
                <h2 className="text-2xl font-bold text-foreground mb-4 flex items-center gap-3">
                  <button 
                    onClick={() => toggleProgress('cloud-run')}
                    className="text-muted-foreground hover:text-teal-500 transition-colors"
                  >
                    {progress.includes('cloud-run') ? (
                      <CheckCircle2 className="w-6 h-6 text-teal-500" />
                    ) : (
                      <Circle className="w-6 h-6" />
                    )}
                  </button>
                  Cloud Run Deployment
                </h2>
                <p className="text-muted-foreground leading-relaxed mb-4">
                  Cloud Run offers serverless container deployment with automatic scaling and pay-per-request pricing:
                </p>

                <CodeBlock 
                  filename="app.py"
                  code={`from flask import Flask, request, jsonify
import joblib
import os

app = Flask(__name__)

# Load model at startup
model = joblib.load('model/model.joblib')

@app.route('/predict', methods=['POST'])
def predict():
    """Handle prediction requests."""
    try:
        data = request.get_json()
        instances = data.get('instances', [])
        
        predictions = model.predict(instances)
        
        return jsonify({
            'predictions': predictions.tolist(),
            'status': 'success'
        })
    except Exception as e:
        return jsonify({'error': str(e)}), 500

@app.route('/health', methods=['GET'])
def health():
    """Health check endpoint."""
    return 'OK', 200

if __name__ == '__main__':
    port = int(os.environ.get('PORT', 8080))
    app.run(host='0.0.0.0', port=port)`}
                />

                <CodeBlock 
                  filename="Dockerfile"
                  code={`FROM python:3.9-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY app.py .
COPY model/ ./model/

ENV PORT=8080

EXPOSE 8080

CMD ["gunicorn", "--bind", "0.0.0.0:8080", "app:app"]`}
                />

                <p className="text-muted-foreground leading-relaxed my-4">
                  Deploy to Cloud Run:
                </p>

                <CodeBlock 
                  language="bash"
                  filename="terminal"
                  code={`# Build and push container
gcloud builds submit --tag gcr.io/PROJECT_ID/ml-predictor

# Deploy to Cloud Run
gcloud run deploy ml-predictor \\
  --image gcr.io/PROJECT_ID/ml-predictor \\
  --platform managed \\
  --region us-central1 \\
  --memory 2Gi \\
  --cpu 2 \\
  --min-instances 1 \\
  --max-instances 10 \\
  --concurrency 80 \\
  --allow-unauthenticated`}
                  showLineNumbers={false}
                />

                <Callout type="info" title="Cost Comparison">
                  Cloud Run charges only for actual request processing time, making it cost-effective 
                  for variable workloads. Vertex AI endpoints charge continuously but offer lower latency.
                </Callout>
              </section>

              {/* Auto Scaling Section */}
              <section id="auto-scaling" className="mb-16">
                <h2 className="text-2xl font-bold text-foreground mb-4 flex items-center gap-3">
                  <button 
                    onClick={() => toggleProgress('auto-scaling')}
                    className="text-muted-foreground hover:text-teal-500 transition-colors"
                  >
                    {progress.includes('auto-scaling') ? (
                      <CheckCircle2 className="w-6 h-6 text-teal-500" />
                    ) : (
                      <Circle className="w-6 h-6" />
                    )}
                  </button>
                  Auto Scaling
                </h2>
                <p className="text-muted-foreground leading-relaxed mb-4">
                  Configure auto-scaling for Vertex AI endpoints:
                </p>

                <CodeBlock 
                  filename="auto_scaling.py"
                  code={`from google.cloud import aiplatform

# Update deployed model with auto-scaling
endpoint = aiplatform.Endpoint(endpoint_name="YOUR_ENDPOINT_ID")

# Configure auto-scaling
endpoint.update(
    traffic_split={"deployed-model-id": 100},
    deployed_models_to_update=[{
        "id": "deployed-model-id",
        "automatic_resources": {
            "min_replica_count": 1,
            "max_replica_count": 10
        }
    }]
)

# Or use dedicated resources with custom scaling
model.deploy(
    endpoint=endpoint,
    deployed_model_display_name="v2-autoscale",
    machine_type="n1-standard-4",
    min_replica_count=2,
    max_replica_count=20,
    accelerator_type="NVIDIA_TESLA_T4",
    accelerator_count=1,
    autoscaling_target_cpu_utilization=70,
    autoscaling_target_accelerator_duty_cycle=60
)

print("Auto-scaling configured")`}
                />

                <div className="grid grid-cols-1 md:grid-cols-2 gap-4 mt-6">
                  <div className="p-4 rounded-xl bg-blue-500/10 border border-blue-500/20">
                    <div className="font-semibold text-blue-400 mb-1">CPU-Based Scaling</div>
                    <div className="text-sm text-muted-foreground">Scale based on CPU utilization threshold</div>
                  </div>
                  <div className="p-4 rounded-xl bg-purple-500/10 border border-purple-500/20">
                    <div className="font-semibold text-purple-400 mb-1">GPU-Based Scaling</div>
                    <div className="text-sm text-muted-foreground">Scale based on accelerator duty cycle</div>
                  </div>
                </div>
              </section>

              {/* Load Balancing Section */}
              <section id="load-balancing" className="mb-16">
                <h2 className="text-2xl font-bold text-foreground mb-4 flex items-center gap-3">
                  <button 
                    onClick={() => toggleProgress('load-balancing')}
                    className="text-muted-foreground hover:text-teal-500 transition-colors"
                  >
                    {progress.includes('load-balancing') ? (
                      <CheckCircle2 className="w-6 h-6 text-teal-500" />
                    ) : (
                      <Circle className="w-6 h-6" />
                    )}
                  </button>
                  Load Balancing
                </h2>
                <p className="text-muted-foreground leading-relaxed mb-4">
                  Set up global load balancing for multi-region deployments:
                </p>

                <CodeBlock 
                  language="bash"
                  filename="terminal"
                  code={`# Create a serverless NEG for Cloud Run
gcloud compute network-endpoint-groups create ml-neg \\
  --region=us-central1 \\
  --network-endpoint-type=serverless \\
  --cloud-run-service=ml-predictor

# Create backend service
gcloud compute backend-services create ml-backend \\
  --global

# Add NEG to backend
gcloud compute backend-services add-backend ml-backend \\
  --global \\
  --network-endpoint-group=ml-neg \\
  --network-endpoint-group-region=us-central1

# Create URL map
gcloud compute url-maps create ml-url-map \\
  --default-service ml-backend

# Create HTTPS proxy
gcloud compute target-https-proxies create ml-https-proxy \\
  --url-map=ml-url-map \\
  --ssl-certificates=your-ssl-cert

# Create forwarding rule
gcloud compute forwarding-rules create ml-forwarding-rule \\
  --global \\
  --target-https-proxy=ml-https-proxy \\
  --ports=443`}
                  showLineNumbers={false}
                />
              </section>

              {/* Monitoring Section */}
              <section id="monitoring" className="mb-16">
                <h2 className="text-2xl font-bold text-foreground mb-4 flex items-center gap-3">
                  <button 
                    onClick={() => toggleProgress('monitoring')}
                    className="text-muted-foreground hover:text-teal-500 transition-colors"
                  >
                    {progress.includes('monitoring') ? (
                      <CheckCircle2 className="w-6 h-6 text-teal-500" />
                    ) : (
                      <Circle className="w-6 h-6" />
                    )}
                  </button>
                  Monitoring & Logging
                </h2>
                <p className="text-muted-foreground leading-relaxed mb-4">
                  Monitor your endpoints with Cloud Monitoring:
                </p>

                <CodeBlock 
                  filename="monitoring.py"
                  code={`from google.cloud import monitoring_v3
from google.cloud import aiplatform
from datetime import datetime, timedelta

def get_endpoint_metrics(project_id: str, endpoint_id: str):
    """Retrieve metrics for a Vertex AI endpoint."""
    
    client = monitoring_v3.MetricServiceClient()
    project_name = f"projects/{project_id}"
    
    # Get prediction latency
    interval = monitoring_v3.TimeInterval({
        "end_time": {"seconds": int(datetime.now().timestamp())},
        "start_time": {"seconds": int((datetime.now() - timedelta(hours=1)).timestamp())}
    })
    
    results = client.list_time_series(
        request={
            "name": project_name,
            "filter": f'resource.type="aiplatform.googleapis.com/Endpoint" AND metric.type="aiplatform.googleapis.com/prediction/online/response_latencies"',
            "interval": interval,
            "view": monitoring_v3.ListTimeSeriesRequest.TimeSeriesView.FULL
        }
    )
    
    for result in results:
        print(f"Metric: {result.metric.type}")
        for point in result.points:
            print(f"  Latency: {point.value.distribution_value.mean}ms")

def create_alert_policy(project_id: str, endpoint_name: str):
    """Create alerting policy for high latency."""
    
    client = monitoring_v3.AlertPolicyServiceClient()
    
    policy = monitoring_v3.AlertPolicy(
        display_name=f"High Latency - {endpoint_name}",
        conditions=[
            monitoring_v3.AlertPolicy.Condition(
                display_name="Prediction latency > 500ms",
                condition_threshold=monitoring_v3.AlertPolicy.Condition.MetricThreshold(
                    filter='resource.type="aiplatform.googleapis.com/Endpoint" AND metric.type="aiplatform.googleapis.com/prediction/online/response_latencies"',
                    comparison=monitoring_v3.ComparisonType.COMPARISON_GT,
                    threshold_value=500,
                    duration={"seconds": 60},
                    aggregations=[{
                        "alignment_period": {"seconds": 60},
                        "per_series_aligner": monitoring_v3.Aggregation.Aligner.ALIGN_PERCENTILE_95
                    }]
                )
            )
        ],
        notification_channels=[f"projects/{project_id}/notificationChannels/YOUR_CHANNEL"]
    )
    
    return client.create_alert_policy(name=f"projects/{project_id}", alert_policy=policy)`}
                />
              </section>

              {/* Security Section */}
              <section id="security" className="mb-16">
                <h2 className="text-2xl font-bold text-foreground mb-4 flex items-center gap-3">
                  <button 
                    onClick={() => toggleProgress('security')}
                    className="text-muted-foreground hover:text-teal-500 transition-colors"
                  >
                    {progress.includes('security') ? (
                      <CheckCircle2 className="w-6 h-6 text-teal-500" />
                    ) : (
                      <Circle className="w-6 h-6" />
                    )}
                  </button>
                  Security Best Practices
                </h2>
                <p className="text-muted-foreground leading-relaxed mb-4">
                  Secure your ML endpoints:
                </p>

                <div className="space-y-4 mb-6">
                  <div className="p-4 rounded-xl bg-card/50 border border-border">
                    <h4 className="font-semibold text-foreground mb-2">VPC Service Controls</h4>
                    <p className="text-sm text-muted-foreground mb-3">
                      Restrict access to endpoints within a VPC perimeter:
                    </p>
                    <CodeBlock 
                      language="bash"
                      filename="terminal"
                      code={`gcloud access-context-manager perimeters create ml-perimeter \\
  --resources=projects/PROJECT_NUMBER \\
  --restricted-services=aiplatform.googleapis.com`}
                      showLineNumbers={false}
                    />
                  </div>

                  <div className="p-4 rounded-xl bg-card/50 border border-border">
                    <h4 className="font-semibold text-foreground mb-2">IAM Authentication</h4>
                    <p className="text-sm text-muted-foreground">
                      Require authentication for endpoint access. Use 
                      <InlineCode>roles/aiplatform.user</InlineCode> for prediction-only access.
                    </p>
                  </div>

                  <div className="p-4 rounded-xl bg-card/50 border border-border">
                    <h4 className="font-semibold text-foreground mb-2">CMEK Encryption</h4>
                    <p className="text-sm text-muted-foreground">
                      Use Customer-Managed Encryption Keys for model artifacts and prediction data.
                    </p>
                  </div>
                </div>
              </section>

              {/* Complete Example Section */}
              <section id="example" className="mb-16">
                <h2 className="text-2xl font-bold text-foreground mb-4 flex items-center gap-3">
                  <button 
                    onClick={() => toggleProgress('example')}
                    className="text-muted-foreground hover:text-teal-500 transition-colors"
                  >
                    {progress.includes('example') ? (
                      <CheckCircle2 className="w-6 h-6 text-teal-500" />
                    ) : (
                      <Circle className="w-6 h-6" />
                    )}
                  </button>
                  Complete Example
                </h2>
                <p className="text-muted-foreground leading-relaxed mb-4">
                  End-to-end deployment with monitoring:
                </p>

                <CodeBlock 
                  filename="complete_online_gcp.py"
                  code={`from google.cloud import aiplatform
from google.cloud import monitoring_v3
import time

# Configuration
PROJECT_ID = "your-project-id"
REGION = "us-central1"
BUCKET = f"gs://{PROJECT_ID}-models"

# Initialize
aiplatform.init(project=PROJECT_ID, location=REGION)

# 1. Upload model
print("Uploading model...")
model = aiplatform.Model.upload(
    display_name="production-model",
    artifact_uri=f"{BUCKET}/model-v1/",
    serving_container_image_uri="us-docker.pkg.dev/vertex-ai/prediction/sklearn-cpu.1-0:latest",
)

# 2. Create endpoint
print("Creating endpoint...")
endpoint = aiplatform.Endpoint.create(
    display_name="production-endpoint",
    description="Production ML endpoint"
)

# 3. Deploy with auto-scaling
print("Deploying model...")
model.deploy(
    endpoint=endpoint,
    deployed_model_display_name="v1",
    machine_type="n1-standard-4",
    min_replica_count=2,
    max_replica_count=10,
    traffic_percentage=100,
    sync=True
)

# 4. Test predictions
print("\\nTesting predictions...")
test_instances = [
    {"feature1": 1.0, "feature2": 2.0, "feature3": 3.0},
    {"feature1": 4.0, "feature2": 5.0, "feature3": 6.0}
]

predictions = endpoint.predict(instances=test_instances)
print(f"Predictions: {predictions.predictions}")

# 5. Set up monitoring
print("\\nConfiguring monitoring...")
monitoring_client = monitoring_v3.AlertPolicyServiceClient()

alert_policy = monitoring_v3.AlertPolicy(
    display_name="Production Endpoint Alerts",
    conditions=[
        monitoring_v3.AlertPolicy.Condition(
            display_name="High Latency",
            condition_threshold=monitoring_v3.AlertPolicy.Condition.MetricThreshold(
                filter=f'resource.type="aiplatform.googleapis.com/Endpoint"',
                comparison=monitoring_v3.ComparisonType.COMPARISON_GT,
                threshold_value=1000,
                duration={"seconds": 60}
            )
        )
    ]
)

print("\\n✅ Deployment complete!")
print(f"Endpoint: {endpoint.resource_name}")
print(f"Model: {model.display_name}")
print("Auto-scaling: 2-10 replicas")
print("Monitoring: Configured")`}
                />
              </section>

              {/* Next Steps */}
              <section id="next-steps" className="mb-16">
                <h2 className="text-2xl font-bold text-foreground mb-4 flex items-center gap-3">
                  <button 
                    onClick={() => toggleProgress('next-steps')}
                    className="text-muted-foreground hover:text-teal-500 transition-colors"
                  >
                    {progress.includes('next-steps') ? (
                      <CheckCircle2 className="w-6 h-6 text-teal-500" />
                    ) : (
                      <Circle className="w-6 h-6" />
                    )}
                  </button>
                  Next Steps
                </h2>
                <p className="text-muted-foreground leading-relaxed mb-6">
                  You've learned to deploy real-time ML endpoints on GCP. Continue your journey:
                </p>

                <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                  <Link to="/docs/batchdeployment/gcp" className="group p-6 rounded-2xl bg-card/50 border border-border hover:border-foreground/20 hover:shadow-lg hover:shadow-foreground/5 transition-all">
                    <h3 className="font-semibold text-foreground mb-1 group-hover:text-teal-500 transition-colors">
                      Batch Deployment on GCP
                    </h3>
                    <p className="text-sm text-muted-foreground">
                      Process large datasets with batch inference
                    </p>
                  </Link>

                  <Link to="/docs/onlinedeployment/aws" className="group p-6 rounded-2xl bg-card/50 border border-border hover:border-foreground/20 hover:shadow-lg hover:shadow-foreground/5 transition-all">
                    <h3 className="font-semibold text-foreground mb-1 group-hover:text-teal-500 transition-colors">
                      Online Deployment on AWS
                    </h3>
                    <p className="text-sm text-muted-foreground">
                      Compare with AWS SageMaker approach
                    </p>
                  </Link>

                  <Link to="/projects/neural-network" className="group p-6 rounded-2xl bg-card/50 border border-border hover:border-foreground/20 hover:shadow-lg hover:shadow-foreground/5 transition-all">
                    <h3 className="font-semibold text-foreground mb-1 group-hover:text-teal-500 transition-colors">
                      Build a Neural Network
                    </h3>
                    <p className="text-sm text-muted-foreground">
                      Create a model from scratch to deploy
                    </p>
                  </Link>

                  <Link to="/docs" className="group p-6 rounded-2xl bg-card/50 border border-border hover:border-foreground/20 hover:shadow-lg hover:shadow-foreground/5 transition-all">
                    <h3 className="font-semibold text-foreground mb-1 group-hover:text-teal-500 transition-colors">
                      Explore More Docs
                    </h3>
                    <p className="text-sm text-muted-foreground">
                      Browse all documentation
                    </p>
                  </Link>
                </div>
              </section>

              {/* Footer Navigation */}
              <div className="flex items-center justify-between pt-8 border-t border-border">
                <Link to="/docs/model-deployment" className="flex items-center gap-2 text-muted-foreground hover:text-foreground transition-colors">
                  <ArrowLeft className="w-4 h-4" />
                  Back to Model Deployment
                </Link>
                <a 
                  href="https://github.com" 
                  target="_blank" 
                  rel="noopener noreferrer"
                  className="flex items-center gap-2 text-muted-foreground hover:text-foreground transition-colors"
                >
                  Edit on GitHub
                  <ExternalLink className="w-4 h-4" />
                </a>
              </div>
            </article>

            {/* Right Sidebar */}
            <aside className="hidden xl:block w-56 shrink-0">
              <div className="sticky top-28">
                <div className="flex items-center gap-2 mb-4">
                  <List className="w-4 h-4 text-muted-foreground" />
                  <span className="text-sm font-medium text-foreground">On this page</span>
                </div>
                <nav className="space-y-1 mb-6">
                  {sections.map((section) => (
                    <button
                      key={section.id}
                      onClick={() => scrollToSection(section.id)}
                      className={`block w-full text-left text-sm py-1.5 transition-colors ${
                        section.parent ? 'pl-4' : ''
                      } ${
                        activeSection === section.id
                          ? 'text-teal-500 font-medium'
                          : 'text-muted-foreground hover:text-foreground'
                      }`}
                    >
                      {section.title}
                    </button>
                  ))}
                </nav>
              </div>
            </aside>
          </div>
        </div>
      </main>
      
      <Footer />
    </div>
  );
};

export default OnlineDeploymentGCP;
